### ISSUE TITLE
[Q] What is equivelent to pandas to_datetime in Vaex ?

### ISSUE THREAD

**Issue by ttpro1995** [vaexio/vaex#1011]
Let the data be 

```
meowdate,id
2/12/2020,1
4/20/2020,2
```

Here is how I get the date with pandas

```
df_pd = pd.read_csv("date.txt")
pd.to_datetime(df_pd['meowdate'], format=date_format)
```

result 
```
0   2020-02-12
1   2020-04-20
Name: meowdate, dtype: datetime64[ns]
```
However I am trying to do the same with Vaex

```
df_vaex = vaex.read_csv("date.txt")
pd.to_datetime(df_vaex['meowdate'], format=date_format)
```

It show error
```
ValueError: time data 'meowdate' does not match format '%m/%d/%Y' (match)
```

Full error goes [here](https://gist.github.com/ttpro1995/0227c70d8665a7ac1b137f6050ba8295). It didn't work out of the box. 

I would like to know if there are a function to parse an string column into datetime64, with custom format (example: %m/%d/%Y)

**Comment by ttpro1995** [comment]
I also ask on [Stackoverflow](https://stackoverflow.com/questions/64424547/what-is-vaex-function-to-parse-string-to-datetime64-which-equivalent-to-pandas)

**Comment by JovanVeljanoski** [comment]
Hi

Actually, if you looks `pandas.read_csv` there are few options about parsing datetime columns directly while reading. Since vaex wraps this method, you can use those same options there too.

Something like: `df = vaex.read_csv(path_to_file, parse_dates=['meowdate'])` should just work.

Vaex is a different implementation compared to pandas, you can't simply mix me methods/functions of one with the other.

Alternatively you can maybe use string operations (those are blazing fast in vaex), to get the column in the right format to be recognized by `np.datetime64`, but should not be necessary if you use the `parse_dates` option from above.

I hope this helps.

**Comment by ttpro1995** [comment]
Here is what I do, with custom datetime format. Custom date_format is required (from user). 


```
date_format = "%m/%d/%Y"

def column_to_datetime(datetime_str):
    return np.datetime64(datetime.strptime(datetime_str, date_format))

df_vaex['meowdate_parsed'] = df_vaex['meowdate'].apply(column_to_datetime)
```

It worked. However, please check if my code is fit with Vaex best practices for effiency ?

**Comment by JovanVeljanoski** [comment]
I would suggest to benchmark this yourself, and please share the results if you d -  I am curious myself.

In general we do not recommend using apply, since it is not really parallelisable, and we think of it as "the last resort" in a way.  

An alternative would be to manipulate the string expression and get it into a format on which you can simply run
`df[date_column] = df['string_date_column'].astype('datetime64')`

I naively would expect this to run faster perhaps, but really not sure.

In most cases, what you want to do is convert the data from CSV to HDF5,  and during that conversion take care of all the dtypes that are relevant to you. Once you export to HDF5, with the right type, things will go much faster in any case. 

I will close this since it is not longer a technical problem.
Thanks!
