### ISSUE TITLE
[BUG-REPORT] Cannot .dropna() with numeric column name 

### ISSUE THREAD

**Issue by ttpro1995** [vaexio/vaex#1013]
**Description**
Cannot call .dropna() when column name is numeric. 

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
```

 - Vaex was installed via: **pip** 
 - OS: Ubuntu 18.04 

**Additional information**

data file with_index.txt
```
index,1000,1001,1002
0,23131231.0,123333.0,12223.0
1,2882888.0,2634464.0,175849123.0
4,,23572272.0,222024157.0
5,,18376658.0,3458069763.0
6,,344191950.0,116723674.0
7,,233358477.0,1324575135.0
8,,2238510619.0,123177175.0
```

```
import vaex
df_vaex = vaex.from_csv('with_index.txt', index_col='index')
df_vaex.dropna()
```

Have error: 

```
NameError: name 'col_1000' is not defined
```

Full error [log](https://gist.github.com/ttpro1995/a9b2b98836178cad5886129e06a3047c) (very long exception) 

The bug only happen when column name is numeric. If we change column name to alphabet, the code above can run.

```
index,ee,aa,xx
0,23131231.0,123333.0,12223.0
1,2882888.0,2634464.0,175849123.0
4,,23572272.0,222024157.0
5,,18376658.0,3458069763.0
6,,344191950.0,116723674.0
7,,233358477.0,1324575135.0
8,,2238510619.0,123177175.0

```

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for the report. I think this is indeed a bug, and already opened a PR with a test for this. 
@maartenbreddels please adjust the priority differently if you see fit.

@ttpro1995 Due to the nature of how vaex works, it is best to avoid column names that are not word-like. While we make our best effort to support a variety of column names, it can be very very challenging to allow this to work smoothy with the expression system of vaex (which is one of the best things about vaex if you ask me). 

When reading a csv without a header, you can provide `names`, which is a list of column names (the way you want the columns to be called). 

In any case, I hope we can fix this.
Thanks!

**Comment by robocioaca** [comment]
This issue appears to be fixed in the _current_ trunk. While trying to retrace the error example steps:

```
import vaex

df_vaex = vaex.from_csv('with_index.txt', index_col='index')
print(vaex.__version__, '\n\n')
print('original: \n\n',df_vaex, '\n\n')
print('cleaned: \n\n',df_vaex.dropna())
```

I get the following **correct** output 😄  :

```
{'vaex': '4.2.0', 'vaex-core': '4.2.0', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.1', 'vaex-astro': '0.8.1', 'vaex-ui': '0.3.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.12.0', 'vaex-graphql': '0.2.0'} 


original: 

   #           1000              1001             1002
  0    2.31312e+07  123333            12223
  1    2.88289e+06       2.63446e+06      1.75849e+08
  2  nan                 2.35723e+07      2.22024e+08
  3  nan                 1.83767e+07      3.45807e+09
  4  nan                 3.44192e+08      1.16724e+08
  5  nan                 2.33358e+08      1.32458e+09
  6  nan                 2.23851e+09      1.23177e+08 


cleaned: 

   #         1000              1001             1002
  0  2.31312e+07  123333            12223
  1  2.88289e+06       2.63446e+06      1.75849e+08
```

Kudos to whatever @maartenbreddels already did!
