### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'verify_ssl' when reading from s3

### ISSUE THREAD

**Issue by kaburelabs** [vaexio/vaex#1053]
Hi fellows,

I have installed the new versions of Vaex and it's not working for me as I was expecting; 

My objective is to read all files with a specific name path;

STEPS TO REPRODUCE: 
    1 - conda create --name test-vaex python=3.8
    2 - conda activate test-vaex
    3 - pip install vaex-core==4.0.0a5
    4.a - pip install vaex-hdf5 --pre
    4.b - pip install s3fs
    5 - conda install ipykernel
    5 - python -m ipykernel install --user --name=test-vaex
    6 - jupyter notebook

```
import vaex

aws_access_key_id="****************"
aws_secret_access_key="**********************************"

tmp = vaex.open("s3://bucket-name/folder/customer_table_level_*.hdf5", fs_options={'access_key': aws_access_key_id, 'secret_key': aws_secret_access_key})

```

This code is returning the error below: 
![image](https://user-images.githubusercontent.com/24701735/98983901-3a1ae180-2500-11eb-9527-4d8ba5159d38.png)

![image](https://user-images.githubusercontent.com/24701735/98983965-4b63ee00-2500-11eb-88db-09caaf3b05da.png)

I don't know why it's happening, could someone help me to solve it?

**Comment by maartenbreddels** [comment]
For debug/education purposes on how to attack problems like this:
See how that last line (301) calls aiohttp.TCPConnector? This gave me a hint that aiohttp was the problem `pip show aiohttp` showed that we have `4.0.0a1` installed, that smells bad. Running `$ pip install aiohttp==` shows that 3.7.2 is the last stable release, installing that with `$ pip install aiohttp==3.7.2` solved the problem 🙌 .

The reason we get that dependency, is because vaex-hdf5 brings it in, via `gcsfs`. I think we should not have that as a hard dependency, since it can only give extra issues (agreed @JovanVeljanoski ?). They should not be dependencies of vaex-hdf5 anyway, but optional dependencies of vaex-core instead. I'll open a PR for this.

**Comment by kaburelabs** [comment]
It worked, Maarten, thank you very much!!!

The problem now is that it triggered another error:
`ArrowInvalid: Cannot parse URI: 's3://app-bucket-demo-workflows/hdf5/customer_level_table_for_export_2020-08-01 00_00_00.hdf5'`

![image](https://user-images.githubusercontent.com/24701735/99107799-29806f00-25c5-11eb-8753-22079b592226.png)

![image](https://user-images.githubusercontent.com/24701735/99107951-60ef1b80-25c5-11eb-97b6-cb4dfd4d628d.png)

Maybe should I create a new Issue?

**Comment by maartenbreddels** [comment]
There is a space on the filename, that is not supported.
