### ISSUE TITLE
[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by SergeyPenza** [vaexio/vaex#1109]
Hi.
Is it possible to plot long time series with Vaex?  I have studied the examples, tutorial, and API could not find how to plot interactive time series plot. Interactive: zoom in zoom out a ROI. I have a waveform with 700M to 1B points.

**Comment by JovanVeljanoski** [comment]
Hi,

Sorry for taking a long time to reply to this.

Right now, there is no such an interactive plot just out of the box with vaex. We have been thinking for a while to provide a set of interactive plots (like the heatmap widget plot available now) for various cases, but has not yet happened. 

But the good news is that you could use vaex as the "backend" and develop something that will suite your needs quite quite quickly with plotly. 

The way I understand this is:  you have 2 columns, one is the date/time column, and the other one has the values you wanna see. Then you can plot say, a histogram using plotly (so you get interactivity out of the box), when plotting the whole data.

You can program a callback such that, when you zoom/pan on the plotly plot, vaex will recompute the histogram, and the plot will update. You can check the plotly docs on how to do this, it is quite simple. 

So when you zoom sufficiently, you can switch from displaying a histogram to displaying a line plot. 

In your call back function you can do all of this, calculate the data to be visualised (histogram or otherwise) using vaex, which will be quite fast!

I hope this at least gives you an idea of what to do. If you have more questions please feel free to write, and I will try my best to reply faster :)

Cheers

**Comment by JovanVeljanoski** [comment]
Will close as stale. Please re-open if needed.
