### ISSUE TITLE
Normalize JSON in Vaex

### ISSUE THREAD

**Issue by foongminwong** [vaexio/vaex#1119]
**Description**
After reading JSON using `vaex.from_json("docs.json")`, one of the columns is a nested JSON, and we would like to normalize it. 

We are able to do it in Pandas using `json_normalize()`. Does Vaex have a similar function to flatten JSON objects?

Thanks!

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 3.0.0
 - Vaex was installed via: pip
 - OS: Windows 10

**Additional information**
Here's an example of how our nested join data looks like after calling `vaex.from_json("docs.json")`
![nested-json](https://user-images.githubusercontent.com/23441795/102441144-ab4c3800-405c-11eb-9524-239fa184df6d.PNG)

**Comment by JovanVeljanoski** [comment]
Hi @foongminwong 

Since JSON's are essentially text files, and can not be memory mapped (i.e. you have to read them in memory anyway), we recommend that one does this initial sorts of data manipulations related to data reading with pandas, and then use `vaex.from_pandas_df`. 

`vaex.from_json` is simply a wrapper around `pandas.read_json` for convenience, but in some cases (like yours) a one-liner may not be necessarily possible. 

Improvements or suggestions are welcome if you can think of any!
Thanks!
