### ISSUE TITLE
Cannot open hdf5 file

### ISSUE THREAD

**Issue by achrafmasmoudi** [vaexio/vaex#1131]
I get this error OSError: Cannot open sell_data.hdf5 nobody knows how to read it. when I load hdf5 file 

**Description**
i upgrade my vaex version from 3.0.0 to 4.0.0a6 and when I tested my code I get this error 

**Software information**
 - Vaex version : 'vaex': '4.0.0a6',
 'vaex-core': '4.0.0a11',
 'vaex-viz': '0.5.0.dev1',
 'vaex-hdf5': '0.7.0a5',
 'vaex-server': '0.4.0a1',
 'vaex-astro': '0.8.0.dev1',
 'vaex-jupyter': '0.6.0.dev1',
 'vaex-ml': '0.11.0a4',
 'vaex-arrow': '0.5.1'
 - Vaex was installed via: pip 
 
 - OS: windows 10

**Comment by JovanVeljanoski** [comment]
Can you please try the latest alpha?

**Comment by foooooooooooooooobar** [comment]
I'm seeing this too with this code:
````
    bx = vaex.open("bx.hdf5")
````

**Comment by JovanVeljanoski** [comment]
Some suggestions: please see the [FAQ](https://vaex.io/docs/faq.html) about common problems with hdf5 (if created with pandas for example).

Please upgrade to the latest version of vaex.

Will close as stale. Please re-open if needed.

**Comment by oliwhi** [comment]
This issue is unresolved.

vaex was working fine yesterday, today it was telling me I needed to downgrade my numpy to 1.x (?)
I downgraded it, seemed to work.
I had to install vaex-core 4.18.1 otherwise it wouldn't install due to wheel build errors (?) 
```
vaex-core                4.18.1
vaex-viz                 0.5.4
```

Problem: I export a .csv to .hdf5 file format, I can run `pd.read_hdf` on the file and print the dataframe just fine, the data is properly converted, but when I run `vaex.open(filename.hdf5)` it gives me 
```
OSError: Cannot open filename.hdf5 nobody knows how to read it.
```
Not sure why pandas can open it but vaex can't, as I thought vaex uses pandas on the backend. Must be a problem with vaex.
