### ISSUE TITLE
Vaex on ARM

### ISSUE THREAD

**Issue by seekingdeep** [vaexio/vaex#1214]
Hi there,
- Can Vaex be used on an arm-based device such as Raspberry Pi?
- How would i install or build?

**Comment by maartenbreddels** [comment]
Hi,

I think that should be no problem, does:
https://vaex.io/docs/installing.html
help?

Regards,

Maarten

**Comment by nuena** [comment]
@maartenbreddels this does not fully help, no. Trying to install using Miniforge (since Anaconda and miniconda don't work on my Raspberry for whatever reason results in the following output:

```
 conda install -c conda-forge vaex                                                                                                 


Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
Note that the missing packages are not truncated, there is simply no output. 

Alternatively: 
```
conda install -c conda-forge vaex-core vaex-viz vaex-jupyter vaex-server vaex-hdf5 vaex-ml                                         ──(Wed,Dec22)─┘
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vaex-core

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-aarch64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

There is no package for aarch64 in anaconda.org (https://anaconda.org/conda-forge/vaex-core) - it's therefore not surprising that the installation fails. I don't know if it's possible to install it using conda with other sets of parameters, since I don't know anything about conda. 

Can you please double-check that the instructions are indeed fully valid for ARM devices, and if not update the instructions? It appears as if an installation through pip works, so a short hint like "ARM users please use pip" would be great.

**Comment by maartenbreddels** [comment]
Vaex is not pre build on conda-forge, you need to build it yourself.

**Comment by nuena** [comment]
Uhm, can you elaborate how the installation instructions as per your initial link should be interpreted then? After all, it says: 

`Short version
Anaconda users: conda install -c conda-forge vaex`

**Comment by maartenbreddels** [comment]
you should follow the developer instructions (https://vaex.io/docs/installing.html) , that includes building it. Prebuild is only available for intel or Apple silicon.

Although we should be able to build aarch64 wheels.
https://cibuildwheel.readthedocs.io/en/stable/options/#archs

**Comment by seekingdeep** [comment]
Vaex should consider an arm release officially.
Even Microsoft have officially released windows for arm, and lightgbm for arm.
Same goes for Ubuntu.
My guess is you can automate the build using Qemu.

**Comment by maartenbreddels** [comment]
Yeah, it's a.possibility if you check the last link I send.
