### ISSUE TITLE
[BUG-REPORT] unique function ignores dropmissing, dropnan and dropna

### ISSUE THREAD

**Issue by keotic** [vaexio/vaex#1278]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
The following code doesn't work as expected:

test_df = vaex.from_arrays(col1 = ['1','2','3','', np.nan])

print(test_df['col1'].unique(dropmissing=True, dropnan=True, dropna=True))

Yields:
['1', '2', '3', '', 'nan']

Expected value:
['1', '2', '3']

Same thing when only using:
print(test_df['col1'].unique(dropna=True))

['1', '2', '3', '', 'nan']

**Software information**
 - Vaex version : '4.1.0'
 - Vaex was installed via: pip
 - OS: OSX

**Comment by JovanVeljanoski** [comment]
Hi, 

Actually this is not a bug. 
What happens is, you are passing a python list into the method `from_arrays`. Passing lists there is not officially supported, since there is no "rule" what can be in an element of a list. Vaex (kind of like a database) expects each column to be of a single data type. 

When you passed your list, which contains strings and floats (the `np.nan`), it will try to cast it a to numpy array of a common dtype. It tries a few strategies, but if no common dtype is found , it falls back to string, so the `np.nan` becomes `"nan"`, as you see in the result of the `unique`. 

So given that now things are strings, it is true that `"nan"` will not be dropped, as it is a string of valid value.  

If you pass for example a list like `[1, 2, 3, np.nan]` you will get the behavior you expect.

I hope this helps.

**Comment by keotic** [comment]
@JovanVeljanoski Thank you for the clear explanation.
How would you suggest to handle missing / empty values when dealing with string columns?

**Comment by JovanVeljanoski** [comment]
Short answer: in your original example change the `np.nan` to `None`.

In vaex strings are handled by apache arrow, and missing values are represented by mask (similar to numpy masked arrays). 

Long answer :
Which is why we make the distinction between missing, NaN, and NA (not available). 

`np.nan` is not "missing" technically speaking, even though it has been used quite a lot that way in numpy/pandas. It can for example mean invalida value (like division by zero). Missing values (for example lack of a measurement, or api failure), are masked values in vaex, regardless of type (can be string, numeric types etc.). 

So for floats for example, you can have both `np.nan` and missing (masked) values. NaN (`np.nan`) can mean that, for example a measurement was made but it was a bad value (not a number, or some division by zero and the like), while missing value can denote that no measurement was made.

If you want to put everything under one umbrella, this is where `dropna` or `fillna` (NA meaning Not Available) comes in, which is the union of NaN and missing. 

I hope this makes sense.
