### ISSUE TITLE
[FEATURE-REQUEST] pd.to_numeric like functionality

### ISSUE THREAD

**Issue by argenisleon** [vaexio/vaex#1331]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
I would like to convert a column with strings/numbers to an integer/float when possible.
For example:
```
[1.2, "3", 4, "Hi!"]
```
will be converted to 
```
[1, 3, 4, np.nan]
```

In pandas you could:
pd.to_numeric(series, errors="ignore", downcast="float")

**Is your feature request related to a problem? Please describe.**
I would like to parse entire columns from string/numeric values to numeric values.

**Comment by JovanVeljanoski** [comment]
Hi, 

So vaex expects that the columns are already of a single type, kind of like a database. So one should never had data of the type you suggest. We tried to support it in the past, and we found it to be a bad idea generally and hurts performance big time. So any support for mixed types that exists currently will be very likely deprecated in the future. 

The expectation is that when importing/converting data to a vaex dataframe, the user should take care of this, specific to their use-case. 

So what happens when reading a csv file or importing a pandas dataframe, vaex tries to find a common data type, and if such a think does not exist, everything will be cast to string. 

So your example would look like this:

```
["1.2", "3", "4", "Hi!"]
```

Then you could ask - how do I cast this to numeric type forcefully? There is no out of the box way to do this in vaex at the moment. `.astype(float)` would work if all data entries are float-compatible. 

One way would be to use a lazyfied version of `pd.to_numeric`, but i have not tested the performance of this function, and how it would behave for trully big data (like 1 billion rows). But if you are interested in such an approach, I can show you / share code of how one can accomplish this. 

If your data fits in memory (or the columns in question) you can just do it directly in memory with `pd.to_numeric` i suppose.

**Comment by argenisleon** [comment]
@JovanVeljanoski,
Thanks for the detailed response.
Any code you can share would be amazing. 
Maybe this is interesting to you. Right now I am using fastnumbers https://github.com/SethMMorton to make the conversion in pandas/dask like:

```
pd.Series(np.vectorize(isintlike)(series).flatten())
```
This is faster than `pd.to_numeric`.

**Comment by JovanVeljanoski** [comment]
Ah in that case, why simply not use `apply`? 

In vaex `apply` is parallelized by default :)

Example:

```python

import vaex
import numpy as np
import fastnumbers

# create a wrapper function
def func(x):
    return fastnumbers.fast_float(x, on_fail=on_fail)

def on_fail(x):
    return np.nan

x = ['1', '2', 'asdf', '-3']
df = vaex.from_arrays(x=x)


df['x1'] = df.x.apply(func)

print(df)

  #  x       x1
  0  1        1
  1  2        2
  2  asdf   nan
  3  -3      -3
```

Would this work?

**Comment by argenisleon** [comment]
Work great, Thanks.

For the record , the `on_fail` function not seems to work
`fastnumbers.fast_float(x, on_fail=on_fail)`
you can use
`fastnumbers.fast_float(x, deafult=np.nan)`

**Comment by JovanVeljanoski** [comment]
Maybe we have different versions of `fastnumbers` ? I didn't notice the `default` argument, so the `on_fail` was the way I got it to work locally. 

But you probably know more about `fastnumbers` than I! In any case, if you got it to work - that's great!
