### ISSUE TITLE
[BUG-REPORT] vaex on jupyter not working

### ISSUE THREAD

**Issue by URIELFMO** [vaexio/vaex#1350]
Hi,

**Description**
I want to know what should I do to work with vaex on a Jupyter notebook, I used to work with vaex on another machine but it doesn't work with my new computer.

I have not found why it crashes my Jupiter notebook. I have uninstalled the package, installed previous versions, create a new venv with only jupyter and vaex installed, and I have tried it also on VSCode.

It is confusing because it works on ipython, as a .py file and when running the Kernel on Jupyter **Restart & Run All**, but when adding a column into the dataframe and stopping for a second then that notebook is stuck, the asterisk in jupyter never goes away.

Either displaying df again or a simple operation 2+2 crashes it.

```
import vaex, numpy as np
x = np.arange(5)
y = x ** 2
df = vaex.from_arrays(x=x, y=y)
df['r'] = df.x**2

df
2+2
```
I can work with a vaex dataframe until I create a new column. I want to know why. Is it my computer or how should I install it?

**Software information**
{'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1',
 'jupyter notebook': 6.3.0}

 - Vaex was installed via: pip install vaex, using the PyCharm Terminal

> Python version: ['3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020)']
> system: Windows
> machine: AMD64
> platform: Windows-10-10.0.17763

Thanks for your attention. I’m looking forward to your reply.

**Additional information**

![image](https://user-images.githubusercontent.com/84098297/118028453-b3b55000-b328-11eb-94b1-c696c3f69565.png)

**Comment by JovanVeljanoski** [comment]
This sounds like an installation issue. Please make sure that the environment you are using for the Jupyter kernel is the same one that PyCharm uses.

I've never used PyCharm so I can't comment, but I've heard several colleagues having problems when trying to manage Python environments via PyCharm.

If it works in ipython, than I am certain that vaex is not the problem here.

I would do a clean install either using pip or (mini)conda/mamba, without involving PyCharm or anything like that in the process. Also make sure that the new environment is really new..

**Comment by JovanVeljanoski** [comment]
Closing as stale. Please reopen if needed
