### ISSUE TITLE
From pandas  -->  Filter and assignment || Filter and concat - not able to produce the desired result. 

### ISSUE THREAD

**Issue by ashvinmanoj** [vaexio/vaex#1494]
Firstly, thanks for introducing Vaex.

I am trying to replicate a pandas syntax but unable to succeed with Vaex. 

(Datafarme['A'])[(Dataframe['A'] == '')] = (Datafarme['B'])[(Dataframe['A'] == '')]

I am trying to fill the empty rows on Column A with values from Column B when row values in column A is empty. 
Expression on left and right produces a result when executed independently, but together the assignment is not working.

Same syntax in vaex gives an error **"Expression" does not support item assignment**

**Alternative:** 
I tried splitting the dataframe into two, DF1 with Column A having empty values and DF2 with column A having non empty values. Then copy Column B into Column A on DF1. Then use DF1.concat(DF2), but this ended in error too

**You have passed in an object for which we cannot determine a fingerprint**

Both column A and B are string. 
I am using Python 3.8.5 on windows with Vaex 4.3.0
Vaex was installed using **pip install vaex** inside my anaconda environment.

Is it possible to achieve the above goal through Vaex?

Regards
Ashvin

**Comment by JovanVeljanoski** [comment]
(this very question was answered in another issue, but since I cant find it i will give a brief answer here).

Vaex dataframes are like "islands". Apart from `join` or `concat` i don't think they interact with each other.

So what you can do is:
- `df1 = df1.join(df2)`, i.e. join the dataframes based on row number (without passing on what to join, the join will happen by stilling the dataframes together). If you do have an index, you can use that. 
- Then use `where` like `df1.func.where(df1.a == df1.b, df1.a)` which has the syntax `df1.func.where(if, then, else)`

Alternatively to the join , you can just add the raw values of the 2nd dataframe to the 1st dataframe, something like
`df1.add_column('new_column', df2.b.values)`
but this will be an in memory operation. 

Depending on your data, one might be faster or more convenient than the other. 

Hope this helps!

**Comment by ashvinmanoj** [comment]
Thanks for the feedback, but I think join and concat will give two different results.  Join will only give the row count of my df1. But I was referring to concatenation so I can get back the same no of rows as the original data frame.

Please correct me if I am wrong.

**Comment by JovanVeljanoski** [comment]
What i suggested will work for the main example you specified: You may need a small step or two to handle duplicate rows etc, but the main concept is the same.  

> I am trying to replicate a pandas syntax but unable to succeed with Vaex. 
> 
> (Datafarme['A'])[(Dataframe['A'] == '')] = (Datafarme['B'])[(Dataframe['A'] == '')]

I don't know how your data looks like in detail, but this is the general approach. Feel free to look around for better solutions tho.

**Comment by JovanVeljanoski** [comment]
Since there is no bug here, i will close this issue. Please feel free to move this to the Discussion section or stackoverflow to discuss approaches on how to tackle your usecase if the above is not what you are after.
