### ISSUE TITLE
So many virtual columns to hdf5 is very slow and memory error if chunk_size is large

### ISSUE THREAD

**Issue by lilyhappily** [vaexio/vaex#1560]
Hi, vaex is mazing. I just started using it. 
I have some problem of virtual columns about exporting to hdf5 file.
I have many virtual columns afer computing in my dataframe. For example, the virtual column of `df['true_or_not']` has many elements of true and flase as boll type. If I run export_hdf5(), the column of `df['true_or_not']` is very slow and may appear memory errors if large chunk_size. I tried df.materialize(''true_or_not'', inplace=True) and is very slow too.
Besides, I have many virtual columns of string type in my df. How can I write them to file fast?
Thanks!

**Comment by JovanVeljanoski** [comment]
Hi!

What you are finding is normal. Virtual columns are just expressions (like mathematical expression). So when you save data to disk, all those expressions are evaluated, and at that moment they take up memory. This is why a smaller chunk size is required. 

Depending on how your virtual columns are created a single virtual column can depend on many other virtual columns. So all of those would need to be evaluated!

However, when you do export the data to disk, those virtual columns are not virtual anymore, but live as data on disk. So working them (exporting, other mathematics etc..) will very fast since the data is simply read from disk!

Anyway, our recommendation in general is: if you use one or more virtual column frequently, do materialize them (if you can afford to memory) or export them to disk, to speed things up. Also the complexity of the expression might come into play. You can also consider jitting (go through the tutorial if you don't know what this is). 

I hope this helps a bit!

**Comment by JovanVeljanoski** [comment]
Closing as stale - please re open if needed.
