### ISSUE TITLE
[BUG-REPORT] diff() behavior with expression is not easy to grasp

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1678]
**Description**
I am trying to save the result of `diff()` in another column of my vDataFrame* and behavior is surprising me.

(* vDataFrame: vaex DataFrame or virtual DataFrame, as you feel it ;))

```python
# Setup
import vaex as vx
import numpy as np
vdf = vx.from_arrays(x=np.array([1,2,3]))

# Test
vdf.diff(1, column='x')
Out[47]:                                                # so far, so good
  #  x
  0  --
  1  1
  2  1

vdf.diff(1, column='x')['x']
Out[48]: 
Expression = x
Length: 3 dtype: int64 (column)
-------------------------------
0  --                                                       # so far, still ok
1   1
2   1

# Let's record that then.
vdf['diff'] = vdf.diff(1, column='x')['x']
vdf['diff']
Out[51]: 
Expression = diff
Length: 3 dtype: int64 (column)
-------------------------------
0  1                                                       # oh, what is wrong now?
1  2
2  3
```
I was expecting the `diff` column to contain the result of the `diff()` but it contains the initial column.

As a workaround, if I actually keep the result of `diff()` as a 'separate' vDataFrame, and then extract the column of interest, it works.

```python
vdf2 = vdf.diff(1, column='x')
vdf2['x']
Out[57]: 
Expression = x
Length: 3 dtype: int64 (column)
-------------------------------
0  --
1   1
2   1
```

I will go on my calculations with `vdf2`, and keep separate my initial `vdf`, this is fine.
But shouldn't we be able to keep results of the diff alongside the initial column in the same vDataFrame? (maybe this is not a bug report, but a feature request?)

**Software information**
 - Vaex version: 4.5.1
 - Vaex was installed via: conda-forge 
 - OS: Ubuntu 20.04

**Comment by JovanVeljanoski** [comment]
Hi, 

I do not think what you are seeing is a bug (@maartenbreddels please comment if you think otherwise). 
Understanding this requires a but deeper understanding of vaex.. 

Key point to remember: vaex dataframes are like "islands" (or like sql tables), i.e. they are self contained and expressions from one dataframe can not be simply passed to another dataframe, which what happens in this example when "things don't work".

In short:
When you do `df.diff(...)` this method returns a dataframe. The columns of the dataframe that are shifted are now virtual columns, and they only exist in the dataframe the `diff` method returns. 

You can verify this by running
```python
df = df.diff(1, column='x')
print(df.state_get())
```

What you do for the example that does not work for you, i.e. `vdf['diff'] = vdf.diff(1, column='x')['x']`
is you are taking the expression `"x"`, but you are assigning it to the original  (unshifted) dataframe. The original dataframe does not know that expression has been shifted.. so you get the original one.  So this is kind of equivalent to doing

```python
df = vaex.from_arrays(x=np.array([1,2,3]))
df['diff'] = df['x']
```

To test your understanding you can do for example:
```python
df['diff'] = df.diff(1, column='x', inplace=True)['x']
print(df.state_get())
```

Now the shifting is done in place, so you are effectively passing the expression `x` to the same dataframe, just (shallow) copying it. So you get both `"x"` and `"diff"` to be shifted. 

What I imagine you are trying to accomplish is to have both a shifted and the original (unshifted) expression in the dataframe. For this we recommend to make a copy of the expressions you want to shift, and then shift either those copies or the originals. In vaex everything is an expression/shallow copy, so you will not use extra memory for such operations. 

I hope this makes sense.

**Comment by yohplala** [comment]
Hi Jovan,
Thanks for trying to clarify. Hmm honestly, no I am not sure to understand.

In my understanding, as we modify expressions, a graph keeps being built, recording their virtual state in 'simple form'. (I see vaex like a graph manager, but this is likely where I am wrong).

So when I write
`vdf.diff(1, column='x')['x']` 
with the tail `['x']`, I am expecting vaex to take the graph from the vaex DataFrame that is returned by `vdf.diff(1, column='x')` (so with the `diff` recorded in the graph) and to return this last graph state related to `x`.

Ok, I will remain cautious when I write something. ;)
Thanks again,
Bests,

**Comment by JovanVeljanoski** [comment]
Hah, you do get it tho :)
So everything you said is right! A graph is being built, but the graph is stored in the dataframe object!
So when you do  `vdf.diff(1, column='x')['x']` the graph is stored in the output dataframe, but you are not storing that dataframe anywhere, just accessing the expression. The expression is evaluated relative to that dataframe (which you are not storing). You can see the graph kind of in the `df.state_get()`. So an expression, say `"x"` is evaluated relative to a dataframe which encodes what `x` means, otherwise it is just a string.. (you can think of an expression like an equation, it does not carry the data, the dataframe carries the data). So in your case, you are just carrying the expression (Like a string) and assigning it to a different dataframe where `x` is unshifted..  Don't be confused by the dataframes having the same name, they do not have the same "origin". 

Think of this example:

```
df_a = vaex.from_arrays(x=np.array([1, 2, 3]))
df_b = vaex.from_arrays(x=np.array([100, 200, 300]))
df_a['y'] = df_b['x']
print(df_a)
```

This is essentially what you are doing. But in your case, what is above `df_b` is just not stored anywhere, but you are copying over the expression into another dataframe where that expression has a different meaning. In the above example

```
df_a['y'] = df_b['x']
```

what `df_a` is "thinking" is basically "oh, so i need to create an expression `y` that is the same as expression `x`. But that is relative to `df_a`'s data.

**Comment by yohplala** [comment]
A lot of thanks @JovanVeljanoski for the pugnacity you demonstrate trying to explain... and you do succeed! :)

> you can think of an expression like an equation, it does not carry the data,

Yes, this part is ok. I pictured it when having trouble by not being able to use some specific characters in column name (no `.`, no any mathematical characters, no `$` and so on. Actually, the only character accepted, except for letters and integers is `_`. I tried all the others and was getting error in calculations I was attempting.
At this time, I could read a SO question + answer on the topic, and in the answer, someone (from the dev team I understand, but not you nor Marteens) mentionned the 'column name manager' which was doing the job of taking care of this.
So yes, I 'feel' this part, it seems ok to me.

The explanation that 'clicked' things into place is that one:

> expression x [...] that is relative to df_a's data

_relative_ really is the word, and sheds light on "__the graph is stored in the dataframe object__" deeper implications.

Thanks again, I really appreciate!
Have a good day,
Bests,
