### ISSUE TITLE
[FEATURE-REQUEST] datetime plotting support

### ISSUE THREAD

**Issue by cjc-quant** [vaexio/vaex#1840]
I tried to plot a timeseries with a column "time" with type `datetime64[ns]` with syntax similar to if I were to do the same thing with pandas.

With some dummy data

```
import pandas as pd
import matplotlib.pyplot as plt
import vaex

timeidx = pd.date_range('2020-01-01', periods=100, freq='D')
demand = np.random.randn(100)
ts = pd.DataFrame(data={'time': timeidx, 'demand':demand})
tsv = vaex.from_pandas(ts)
```

Then plotting with...

```
tsv.plot(x='time', y='demand')
plt.show()
```
I receive an `AttributeError: 'numpy.datetime64' object has no attribute 'get'.

I searched for other similar issues, and it seems that the ability to plot time series has not been implemented.

The intended use is for much larger time series data.
I was hoping to request support for time series plotting with a loaded vaex dataframe.

**Comment by JovanVeljanoski** [comment]
It is nice to recognize that vaex is not identical to pandas and that there are some differences. Do not expect 1:1 translation. 

What I assume you want is (following your example):
```python
tsv.viz.scatter('time', 'demand')
```

Vaex trully shines for Viz when you are plotting histograms and heatmaps, since those scale to very large datasets. For other kinds of plots, there is some support via the `df.viz` accessor but they are mostly shortcuts to matplotlib methods. For advanced stuff you should probably get the data out that you need and plot it yourself via your favorite library (matplotlib, plotly, etc..)

**Comment by cjc-quant** [comment]
I was hoping to draw lines rather than a scatter.

The data I'm working with doesn't fit in main memory, so I am unable to directly plot it with a favourite library (matplotlib, plotly, etc..). I was hoping that Vaex could somehow simply the process, by plotting with just-in-time computation.

**Comment by JovanVeljanoski** [comment]
Vaex just takes the data and gives it to matplotlib. It can work and do all kinds of operations on arbitrarily large amounts of data, but for plotting.. 

the exception to this are things like histograms and heatmaps which use aggregate data. 

It might be helpful for you to read through this thread: https://github.com/vaexio/vaex/issues/653

**Comment by cjc-quant** [comment]
Hey thanks, [#643 ](https://github.com/vaexio/vaex/issues/653) was super helpful. I'll close this issue.
