### ISSUE TITLE
unable to open files

### ISSUE THREAD

**Issue by janwyler** [vaexio/vaex#1978]
I tried to open files in hdf5 and pkl format but none of them worked. I alwas get the error ""OSError: Cannot open raw_data/24h/20190101_dl_raw.pkl nobody knows how to read it.". 
What could be the reson for this?

**Comment by JovanVeljanoski** [comment]
Vaex does not support reading pickle files. 

As for hdf5, how did you create it? If you created it via pandas, it will also not work (due to a different schema internally, to what vaex expects). 

You can read more about this in: 
- https://vaex.io/docs/example_io.html
- https://vaex.io/docs/faq.html

**Comment by JovanVeljanoski** [comment]
If at some point the data is pandas, you can do:

```python
df = vaex.from_pandas(pandas_df)
df.export('my_file.hdf5')
```

If the data comes from some machine or process where it is hard to install vaex, you can export (via pandas) to parqet. Vaex can read that (but it comes with a performance penalty since parquet is a compressed format). But you can then export that to hdf5, if you need more performance.

**Comment by janwyler** [comment]
Perfect, I will try that. Thank you a lot!
