### ISSUE TITLE
Ran Out of Memory for Only 15M Rows

### ISSUE THREAD

**Issue by Hasna94** [vaexio/vaex#1985]
Hi, 
I'm trying to run a Vaex xgboost model on colab with a 15M+ row dataset. I read that vaex works with 1Billion+ rows on a single machine. So I'm just trying to understand why my much smaller dataset wasn't able to run before running out of memory. I'm just trying to understand for learning purposes. In what cases would vaex work with a large dataset or is my code wrong?
Code below:
```
import vaex
import pandas as pd
import pyarrow.parquet as pq

from vaex.ml.xgboost import XGBoostModel
paq = pq.read_table('/content/final_df.parquet.gzip')
df_names = vaex.from_arrow_table(paq)
df_names
df_train, df_test = df_names.ml.train_test_split(test_size=0.2, verbose=False)

features = [--40 columns--]
target = 'Y'

params = {'learning_rate': 0.1,
          'max_depth': 3,
          'num_class': 3,
          'objective': 'multi:softmax',
          'subsample': 1,
          'random_state': 42,
          'n_jobs': -1}


booster = XGBoostModel(features=features, target=target, num_boost_round=5, params=params)
booster.fit(df=df_train, evals=[(df_train, 'train'), (df_test, 'test')], early_stopping_rounds=20)

df_test = booster.transform(df_train)
df_test
```

My colab runtime then automatically restarts.

**Comment by JovanVeljanoski** [comment]
Hi, 

Indeed vaex can be used with data comprising billions of rows. 
However, in your case you are using vaex but also using xgboost! `vaex.ml.xgboost` is just a wrapper for xgboost, not a re-implementation. Thus at the training step the data you need for training (or validation) is put in memory to be consumed by xgboost. 

The wrapper is to help make a pipeline and to help with storing the model (to the state file). 

If you need to train a model on very large amount of data, i know that catboost can train bunch of models then average them out (i think this is shown in the docs, and definetely in the docstrings).

Other ideas:
 - use streaming ML models (check out river for example, or simple incremental models offered by sklearn)
 - try this catboost feature (i know it technically works, but I have not really tried it out to comment on the model performance)
 - reduce the data somehow so that it can fit in memory (via feature engineering or subsampling for instance)

**Comment by Hasna94** [comment]
Thanks for your response! Makes sense.
