### ISSUE TITLE
can I use ploty graohs with vaex dataframe ? 

### ISSUE THREAD

**Issue by sanaeO** [vaexio/vaex#2020]
I wanna use a dataframe vaex with ploty express to make a dash app
I don't know if I can do this

df = dfvx.groupby((dfvx.PRO, dfvx.AGE), agg='count')
scatter = px.scatter(df,
                     size="PRO, color="AGE",
                     hover_name="PRO", log_x=True, size_max=50)

the Error : 
ValueError: Value of 'size' is not the name of a column in 'data_frame'. Expected one of [0] but received: count

If there is a solution , let Me know 
thaaank you

**Comment by msbeeman** [comment]
Good morning, yes you can use plotly with vaex to make a dash app. There are a lot of resources out there if you need assistance, in fact the co-founder of vaex has written something on it here: https://medium.com/plotly/interactive-and-scalable-dashboards-with-vaex-and-dash-9b104b2dc9f0

In regards to your error, it looks like you're missing an ending quote after PRO:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/59752826/163673761-2a07c1e3-ce55-40cf-b5f9-3da89402038c.png">

In Python if you ever see a ValueError raised, it's because you gave the function an invalid argument.

**Comment by sanaeO** [comment]
thank you so much for your reply 
I put the ending quote but show the same error

I'm passing in to the parameters the name of my columns of my dataframe (df) , but doesn't work

**Comment by msbeeman** [comment]
@sanaeO Could you send sample data for dfvx?

**Comment by JovanVeljanoski** [comment]
You can't use plotly express directly with a vaex dataframe. This has been
discussed elsewhere on these boards. If you'd like plotly express to
support vaex dataframes, please raise this on the plotly side. There were
some efforts on this..

In the meantime, easiest is to covert the vaex dataframe to pandas (see
docs) after the group by operation. In most cases data for viz should be in
memory anyway.

**Comment by maartenbreddels** [comment]
As Jovan said:

```
px.scatter(vdf.to_pandas_df(), ...)
```
should work
