### ISSUE TITLE
[BUG-REPORT] TypeError: Cannnot export column of type: object

### ISSUE THREAD

**Issue by FarahAmirahJ** [vaexio/vaex#2033]
Hi, Im trying to use vaex for my dataset, we need to merge 5 dataset format  csv, and then I cannot load the data.
I'm using code below;

import vaex
file_path = r'./.csv'
vaex_df = vaex.from_csv(file_path, convert=True, chunk_size=5_000_000)

and then I got type error, 
I attach the screenshot here.
Please kindly advise

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: vaex:4.9.1, 
vaex-astro:0.9.1, 
vaex-core:4.9.1, 
vaex-hdf5:0.12.1, 
vaex-jupyter:0.7.0, 
 vaex-ml:0.17.0, 
vaex-server:0.8.1, 
vaex-viz: 0.5.1
 - Vaex was installed via command prompt virtual env - conda install -c conda-forge vaex
 - OS: Windows Server 16

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).
![1](https://user-images.githubusercontent.com/102510231/165473311-ce0144ac-4c3e-410a-9b63-b6cf4dc9a131.jpg)
![2](https://user-images.githubusercontent.com/102510231/165473320-07ab342a-dffd-4d81-9191-30f7c4cbc307.jpg)

**Comment by JovanVeljanoski** [comment]
dtype object is generally not supported. We tried it in the past, but it leads to a very bad performance and various other problems. 

Some operations may work, but this should be avoided. This has been discussed elsewhere on the issue boards. 

So users are expected do "normalize" their data to dtypes that are supported, kind of like what you would do with databases, before using vaex. Sometimes maybe you can do this within vaex also, but not generally advised (for performance reasons etc..)

**Comment by FarahAmirahJ** [comment]
hi, the issue is solved by changing the csv to hdf file by using command

import vaex
file_path = r'./project1.csv'
col1=['column_name']
vaex_df = vaex.from_csv(file_path, copy_index=False, low_memory=False, usecols=col1)

df_1.export_hdf5(r'./project1.hdf5')

**Comment by JovanVeljanoski** [comment]
Sure but the column(s) you are actually using are not of dtype object.. 

In any case, I am happy you got it working!

**Comment by thebhsu** [comment]
> dtype object is generally not supported. We tried it in the past, but it leads to a very bad performance and various other problems.
> 
> Some operations may work, but this should be avoided. This has been discussed elsewhere on the issue boards.
> 
> So users are expected do "normalize" their data to dtypes that are supported, kind of like what you would do with databases, before using vaex. Sometimes maybe you can do this within vaex also, but not generally advised (for performance reasons etc..)

Hi @JovanVeljanoski, could you point me to which dtypes are supported by vaex, had some trouble searching for it in the docs.

**Comment by JovanVeljanoski** [comment]
@thebhsu  We are updating the docs to answer your question. 

In short: primitive types are supported (int / floats ) from python, numpy and arrow. All strings are converted to arrow. 
From numpy datetime64/32 are supported, with the equivalent side on arrow. Python datetime currently not supported. 
timdelta64 (numpy) and the arrow equivalent (duration) are supported. 

On the arrow side, structs are also supported. 

Numpy arrays and lists are not officially supported, although you will find many things work - so if you really need it you can probably find hacky way to make things work. 

We wan to make more things supported - subject to funding and time. 

The main thing is: objects are not supported (and will not be supported). Maybe sure your data does not have them, and if it does clean it before giving it to vaex.

**Comment by thondeboer** [comment]
I don't understand the issue here...How is it that vaex thinks the dtype of a column is OBJECT? or is this just because behind the scenes you use pandas to convert CSV files and PANDAS decides a column is an OBJECT dtype? Good reason not to use PANDAS if you can't use all the dtypes that PANDAS supports. Is the only reason around this that we have to define the dtype at import? Makes it hard to determine what are OBEJECT types, since in my mind OBJECT==STR so not always sure what PANDAS assumes to be OBJECT

**Comment by JovanVeljanoski** [comment]
Yes, right now vaex uses `pandas.read_csv` under the hood to read csv files.
To understand this better you need to understand how pandas and numpy work, and how an object is created there in the 1st place. I'll give you a hint - try creating a string column using pure numpy :). Pandas is sort of wrapper around numpy, and numpy does not provide true string support.

For a long time pandas did not have a string dtype. It does now, but it is fairly new addition. At the beginning Vaex did not have any support for string either, since the string support in numpy is minimal at best (and fair enough - numpy stands for numerical python after all).

In any case - vaex will try to avoid the creation of an object dtype as much as possible, i.e. if a column can be coerced into string it will be. If such coercion is not possible for whatever reason, a column of dtype object will be created (as backed by numpy).

The `pandas.read_csv` is great tho. It is quite flexible and robust, provides many options. Not the fastest, but speed is a fair price to pay for all the flexibility it provides in my opinion.

We are close to providing support for the pyarrow csv reader in vaex, which will bring a nice performance improvement, and it might be more strict with this whole dtype thing. 

If you are up for writing a csv reader that can be an upgrade over existing solutions - please do so :)
