### ISSUE TITLE
Question: Is Vaex a good option for serving large-size embeddings (100_000_000, 2048)?

### ISSUE THREAD

**Issue by pavelkrizek** [vaexio/vaex#2055]
Thank you for a great library, and sorry for the polluting issues with a general question. I was recently screening technologies for serving large-scale embeddings with shape ~ (100_000_000, 2048) in float and Vaex seems like a sensible option since it doesn't store everything in the memory.

Do you think that it could work efficiently in one of the following scenarios:

1. Filtering just one row based on a unique identifier (i.e. based on the index)
2. Filtering a couple of millions of rows based on unique identifiers

Thank you a lot for any suggestions.

**Comment by JovanVeljanoski** [comment]
Hi, 

That depends what "efficiently" means for you :). But the usecase you describe appears to me to be a nice match for vaex. Best is to benchmark it and see what you think. 

The size of the data is not a problem at all.

**Comment by Ben-Epstein** [comment]
@pavelkrizek That's what I use vaex for. My datasets are generally a bit smaller (5,000,000 X 1,000) but during testing I push it much larger.

A few suggestions:
* use a single column with the embeddings instead of 1 column per embedding value. Vaex does not do well with very high numbers of columns 
* Add strong unit tests comparing to normal numpy operations, as sometimes vaex will behave in ways you dont expect, so it's crucial to validate the math

Here's how I create dataframes for testing
```
import numpy as np
import vaex


# Put in memory
df = vaex.from_arrays(
    id=list(range(1_000_000)),
    emb=np.random.rand(1_000_000, 2048)
)
# Take out of memory -> disk
df.export_hdf5("my_emb.hdf5")
df.close()

# mmap
df = vaex.open("my_emb.hdf5")
df_concat = vaex.concat([df]*100)  # 100 million rows, lazily created
df.export("my_emb_large.hdf5", progress="rich")  # "rich" if you have `rich` installed, otherwise use `progress="vaex"` 
```

**Comment by JovanVeljanoski** [comment]
I will close this, since I believe this question to be answered. Please re-open if needed.
