### ISSUE TITLE
Reserved keywords

### ISSUE THREAD

**Issue by JovanVeljanoski** [vaexio/vaex#219]
We need some protection against reserved Python keywords being used as column names. This can happen when reading an ascii or csv file, or by manually adding a column with a reserved keyword name. 

The keyword "class" can be a common occurrence, especially with ML datasets.

**Comment by alimcmaster1** [comment]
We should be able to use [this](https://docs.python.org/3/library/keyword.html#keyword.iskeyword) -> but do we definitely want to not allow all keywords as column names? Guessing this currently breaks something?

**Comment by maartenbreddels** [comment]
Thanks for the pointer! I think we should do it in 2 phases:
 * rewrite keywords, by appending `_` to the name, I think we should use https://github.com/vaexio/vaex/blob/75c5ccb2bbcda44a82adc5496f55f8dc3f2f1d4b/packages/vaex-core/vaex/utils.py#L558 for this.
 * Allow the expression syntax to use `'self["class"] * 2'` instead of `'class * 2'`, to support reserved/keyword names, this is a bit more tricky, since it more difficult to recognise if a part of an expression corresponds to a column. E.g. we have to recognise that `'self["class"]'` matches the column 'class'.

**Comment by maartenbreddels** [comment]
Fixed by #370
