### ISSUE TITLE
[FEATURE-REQUEST] The join "how" doesn't support "cross" option

### ISSUE THREAD

**Issue by hewittzgh** [vaexio/vaex#2234]
Hi sir, I use the vaex recently. Vaex is a awesome package. But I find that the vaex doesn't support the "cross" option of the join API. I want to cross-join two dataframes like [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html?highlight=merge#pandas.DataFrame.merge).
Can you help me? I really need the feature to build my cryptography system.

**Comment by hewittzgh** [comment]
@maartenbreddels 
@JovanVeljanoski

**Comment by JovanVeljanoski** [comment]
Hi, 

There is indeed no support for a cross join currently. I think it would be great if we could support it. However it is a rather big undertaking (especially to make it memory efficient and performant), and if we take up that task it would block any other development and support for a rather long time. 

We would be happy to take this on if some one is willing to fund or otherwise support this work. Otherwise we want to spend time developing features that we think will impact more people and we put as a higher priority.
