### ISSUE TITLE
[General Question / Potential Bug Report] Groupby operation on Large Dataset

### ISSUE THREAD

**Issue by armandgurgu23** [vaexio/vaex#2276]
Hi Vaex team! Firstly I want to say a big thank you for actively maintaining this project, it appears very promising!

I'm new to Vaex and I've been adopting Vaex for processing and computing statistics on larger datasets. As such I'm not sure whether my usecase is indeed a bug or whether there's something in the docs that I've missed.

## Usecase

I have a large dataset that I partitioned into 200 parquet files where each parquet file contains 1M rows and 6 columns. Each file has an identical schema and the majority of the columns either consist of UUID strings (e.g: uuid.uuid4()) or ordinary strings. For any of these columns there may be duplicated UUID / ordinary string entries. I read in all these files at once using vaex.open().

I'm interested to compute a groupby operation across the entire 200M rows for one of these columns and run a simple count operator to generate some statistics. However my program consistently gets killed when trying to run these operations on one of these columns.

For such a usecase would there be a different serialization format (e.g: arrow file) that might work better to process this data? Or is my issue likely related to requiring more RAM?

## Testing Environment Details
Vaex library used = 4.14
Operating System = Ubuntu 18.04
Specs of machine = 8 core CPU + 16 GiB RAM.

**Comment by JovanVeljanoski** [comment]
Hi,

Thanks for the report! 

That is a bit worrying indeed. 
If this is something you could try: 
 - after you do the `vaex.open()` command, can you export the data as a single parquet file and/or a single hdf5 or arrow file. 

Parquet is good for saving disk space (and thus more efficient to send around a network). For ultimate performance you probably want hdf5, and for close to best performance but interoperability you want arrow format. Vaex works best with a single data file (or a few at least). 

I have tested it with 100s of hdf5 and arrow files, and it runs well, but not with parquet files (at least not with more than 10 or so). 

Also, it would be helpful if you can re-try the operation as you do now (on the 200 files) but as the groupby is going on keep an eye on the RAM usage (via top or htop or the like) and see if it uses memory or not. It might help us narrow down the problem. 


Looking forward to your findings :)

**Comment by JovanVeljanoski** [comment]
Can you share the groupby command?

**Comment by armandgurgu23** [comment]
Sample code snippet below:

```python
import vaex

def main(
    dataset_path:str = 'PATH TO SINGLE 200M HDF5/PARQUET',
):
    dataset = vaex.open(dataset_path)
    print(dataset)
    print('Attempting a groupby operation!')
    print(dataset.groupby(dataset.x, agg='count'))
    return

if __name__ == "__main__":
   main()

```

Where dataset.x represents a column of UUID strings that may contain duplicated entries.

**Comment by JovanVeljanoski** [comment]
Alright, thanks for the info. Can you tell me what is the size of the hdf5 file. 

I have an idea of what might be going on, but you will have to check/confirm this. 

Since you are reading the data from disk (either from parquet or hdf5 file(s) does not matter), vaex will do all the operations out-of-core. So memory usage will be minimal. 

This is true for the groupby operation also. However, the output of the groupby operation, i.e. the resulting dataframe, will be in memory. So you need to make sure that you have enough RAM to house the output of the groupby operation. 

This usually happens when one does groupby on N-dimensions, as then the number of combinations may blow up. Here you do things on a single column, so i thought that should not be a problem. 

However, you said that the `"x"` column is of string type, which gives potential to be quite large. So you need to estimate the size (and memory footprint) of the output dataframe. Some ideas on how to do this:
 - The extreme case is of the `"x"` column not having duplicates. So you can simply do `dataset.materialize("x")`. That will put that column in memory, and see how much that takes. Then you need to add the contribution of as many `int64` samples (for the counts result). 
 - try to calculate the number of unique values via `dataset.x.nunique()`. if that starts to blow up the memory, likely indicates that you can't hold all unique values in memory..  The `limit` parameter of `unique` and `nunique` might come in handy if you want to keep things under control.
 - If the data is similar amongst the individual 200 parquet files, you can try to do the groupby operation on one of them, see what the memory footprint is, and multiply it by 200? (dunno if this will give you a realistic estimate, as there are bunch of assumptions here, but just giving an idea). 

I hope this makes sense. Please let me know what you find.

**Comment by JovanVeljanoski** [comment]
I am trying to reproduce your example by just doing:

```python
import vaex
import uuid

x = [str(uuid.uuid4()) for i in range(200_000_000)]
df = vaex.from_arrays(x=x)
```

And just creating the data in memory takes ~45GB of RAM so.. if the duplicates are relatively rare.. then what I said above is likely the case.

**Comment by armandgurgu23** [comment]
Hi @JovanVeljanoski sorry for the delayed response. I looked into my usecase based on your suggestions above and your belief about the root cause turned out to be true. When moving to a larger AWS instance with more RAM the vaex groupby worked like a charm 😄 (and helped me process the dataset so fast 🔥 ).

I appreciate all the help + insights with debugging this usecase. I will close this ticket for now.

I do have a general question about such usecases where the outputs of a groupby / other vaex operations may cause out of memory issues. Would it be possible for such outputs to be chunked and written to disk instead of loading the full output in RAM if there's a risk to trigger an out of memory issue?
