### ISSUE TITLE
Evaluation method ordering?

### ISSUE THREAD

**Issue by crawftv** [vaexio/vaex#282]
In the [columns section of the tutorial](https://vaex.readthedocs.io/en/latest/tutorial.html#Columns) the code uses `df.evaluate(df.x)`. This expression took much time.  I found `df.x.evaluate()` to work much faster. Is there a reason to use the first way rather than the second?
Thanks

**Comment by maartenbreddels** [comment]
Hi Crawford,

That is really strange, did you try doing it multiple times? Since the last is basically equivalent to the first. Actually, both methods do not perform parallel (yet), for internal reasons. I need to change that, but I actually don't use evaluate single threaded myself.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
I'm assuming this is solved, if not, please reopen.
