### ISSUE TITLE
fillna train issue

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#361]
```
import vaex
from vaex.ml.datasets import load_titanic

df = load_titanic()
train, test = df.split_random(0.7, random_state=42)
train['Age'] = train.Age.fillna(train.Age.mean())

---

AttributeError                            Traceback (most recent call last)
<ipython-input-11-25e6402ed4cd> in <module>
      4 df = load_titanic()
      5 train, test = df.split_random(0.7, random_state=42)
----> 6 train['Age'] = train.Age.fillna(train.Age.mean())

~/.virtualenvs/vaex-sagemaker/lib/python3.6/site-packages/vaex/dataframe.py in __getattr__(self, name)
    216             return self.__hidden__[name].__get__(self)
    217         else:
--> 218             return object.__getattribute__(self, name)
    219 
    220     @property

AttributeError: 'DataFrameArrays' object has no attribute 'Age'
```

**Comment by JovanVeljanoski** [comment]
Hi, 

Please check out #362 as well. 

The reason for this error is that `train.age.mean()` returns an array which is not stored in the state. But fillna expects a single number, so what you can do is:

```
import vaex
import vaex.ml

df = vaex.ml.datasets.load_titanic()
train, test = df.split_random(0.7, random_state=42)
train['age'] = train.age.fillna(float(train.age.mean()))
print(train.age)
```

Please re-open if you encounter any more issues regarding this.

**Comment by xdssio** [comment]
This is a breaking change.
We should at least rethink this.

Either the mean() return a float, or the fillna will change to handle an array. I'm up for the first, but I think letting the user adding a cast is a poor solution.

**Comment by JovanVeljanoski** [comment]
Well.. there is a reason why this is done as it is. For example, 
`df.x.mean(selection=['sel_1', 'sel_2'])` will return the mean for the two selections with 1 pass over the data, and the result will be an array with two values. For a single selection (or no selection), the result is still an array with a single value. 

On the other hand, `fillna` expects a numeric type, you can't fill a missing value with an array right.. so i believe there is nothing wrong with 'fillna'. 

We can indeed discuss if `mean()` should return a float if there is no need for an array, but we need to check the internals for this. @maartenbreddels thoughts?

`mean()` and `fillna()` are two different methods, and while one is not right away pluggable as a kwarg into another is not really a bug. 

I would suggest to close this issue, as it might be confusing (since there is nothing wrong with `fillna`), and maybe re-open another one for what the output for `df.x.mean()` should be for example.. if that makes sense?

**Comment by xdssio** [comment]
I think that if I ask for an expression.mean() I should get a value… I can’t see how returning an array as an answer is intuitively right. 



Jonathan Alexander
Consultant, Data Science
jonathan@xdss.io

**Comment by maartenbreddels** [comment]
well, to have a return value/type depend on the argument is a annoying. Imagine code doing this:
df.mean(....).tolist()

This would work depending on the argument. Maybe we can add an extra argument to do the more intuitive behaviour by default, and change the behaviour if you want this to be a ndarray always (good argument name ideas are welcome!).

**Comment by JovanVeljanoski** [comment]
I will close this since the issue has been resolved.
