### ISSUE TITLE
Recommendation request for non-standard data files

### ISSUE THREAD

**Issue by AlexHenderson** [vaexio/vaex#366]
Hi,
I need to support a number of file formats and would like to read these directly without having to convert to HDF5/Arrow etc. I would also like to read the files without pulling them into memory, ideally reading them remotely; for example on S3, or some other server system. 
Some formats are binary streams and so can be mapped into, once certain headers are processed (to determine the shape, offsets etc). However, some formats are encoded to handle very sparse data (98% zeros). Some use bit patterns to deliver compression. Some use multiple channel numbers to indicate multiple events at the same 'x-value'. 
Are there examples of how to use vaex to lazily map into such files? Is this a scenario where dask could be used to map into the files via functions, with vaex wrapping the dask.enabled functions? 
Any suggestions welcome. 
Thanks, Alex

**Comment by maartenbreddels** [comment]
Dear Alex,

Great questions!
there is some legacy code here which may be useful:
https://github.com/vaexio/vaex/blob/9eb30a944bdf8d0b3d418ab2bc6fb933ba981ba9/packages/vaex-core/vaex/dataset_mmap.py#L226
Which I added to support a custom file format, which has basically a header, and the rest was simply memory mappable data.

Note that this API is not public, and may change, but I am happy to clean that up if you're interested in using that. So currently it is a 'use the source' documentation, but feedback is welcome to publish this up. But basically, if you can call 'addColumn' (yes, camelCasing, it's the oldest code in vaex!), it will do the mmapping for you.

Vaex's columns are either numpy ndarrays or custom Column object, where custom types can be added, see e.g. a purely virtual column here:
https://github.com/vaexio/vaex/blob/9eb30a944bdf8d0b3d418ab2bc6fb933ba981ba9/packages/vaex-core/vaex/column.py#L19
Or a file descriptor based column here:
https://github.com/vaexio/vaex/blob/9eb30a944bdf8d0b3d418ab2bc6fb933ba981ba9/packages/vaex-core/vaex/file/column.py#L34 (which can take an s3fs file descriptor).
For remote data files (s3), I wrap the file descriptor by this decorator:
https://github.com/vaexio/vaex/blob/9eb30a944bdf8d0b3d418ab2bc6fb933ba981ba9/packages/vaex-core/vaex/file/cache.py#L52
That mmaps it to local file (so subsequence access is fast).

If you want to have a custom format, you could do sth like:
```
class MyColumn(vaex.column.Column): 
  # implement dtype/shape/__getitem__
df = vaex.from_arrays(x=np.range(10), y=MyColumn('myfile.data'))
```

The `__getitem__` could then do the reading/unpacking etc. Note that the `__getitem__` should be thread-safe, every thread will call this once it needs a chunk, and that's tricky with file descriptors.

> Is this a scenario where dask could be used to map into the files via functions, with vaex wrapping the dask.enabled functions?

I'm not sure if that is useful since all the parts in vaex are already multithreaded, but maybe I don't completely understand what you want.

Hope this is useful to get going!

Regards,

Maarten

**Comment by AlexHenderson** [comment]
Dear Maarten, 

Sorry for the slow reply and thanks for the great hints and tips! I'll try these out and report back. 

The dask scenario was to implement delayed functions if vaex didn't have that built-in. Looks like the question was redundant. 

Thanks,
Alex

**Comment by maartenbreddels** [comment]
Vaex has it's own delayed decorator, but it will not play nice with dask. But I don't think it's needed as much. I prefer users don't have to use it, otherwise see the tutorial: https://docs.vaex.io/en/latest/tutorial.html

**Comment by maartenbreddels** [comment]
Assuming answered/solved.
