### ISSUE TITLE
not opening vaex file (h5vaex False) -- can't find a bug and no error message

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#46]
Very strangely, I had install vaex on a clean python distribution and now opening a file does not seems to do anything without raising any issue.

```vaex.open('./gums18_mw_S000322010.hdf5')```
I expected to return a ```Hdf5MemoryMapped``` instance but returns ```None```

The file works on a different machine (not going through updates)
```list(h5py.File('gums18_mw_S000322010.hdf5', "r")['/table'].items())```
Does list columns and expected content.

it seems it does not recognize the format for some unknown reasons, below I expect 
```h5vaex True``` which appends on the other machine.

```python
for name, class_ in list(vaex.file.other.dataset_type_map.items()):
     print(name, class_.can_open('./gums18_mw_S000322010.hdf5'))
    
buist False
fits False
h5vaex False
amuse False
gadget-hdf5 False
soneira-peebles False
zeldovich False
ascii False
gadget-plain False
votable False
tap False
```

I do not know if this bug is from Vaex or a bunker library, but I do not have any reported info as to where it fails... any idea?

**Comment by mfouesneau** [comment]
For some reasons pip or conda did not install the git master properly and obtained an old version of at least vaex/file/other.py.

It seems corrected after forcing installation. 
However, I suggest to raise an exception when no format was found.

**Comment by maartenbreddels** [comment]
Hi Morgan,

there are two issues here, one is a change in file format (the latest git has a better format that allows masked values), but it still understands the older format, and that you've resolved yourself.
The second issue is that if it fails to open a file, it will return None. The reason is that every reader is tried, so if the hdf5 one fails, it will try others and does not know for instance that a file should be able to be opened with the hdf5 reader but due to some bug failed to.

I think a better behaviour would be:
 * have a file extension to reader mapping, so .hdf5 will be tried by that specific class
 * if it fails, it will try all the others
 * and if that still didn't get to anything, it will print out the stacktrace by the initial attempt of opening the file

Do you agree?

cheers,

Maarten

**Comment by mfouesneau** [comment]
I don't know if you want to check the extension itself. Sounds a good idea to try. 
I suggested to raise an issue if none of the readers work. Of course that does not fully says why, but at least would not a code run with a None object.

**Comment by maartenbreddels** [comment]
Fixed in master a while ago.
