### ISSUE TITLE
OSError: unable to load hdf5 file

### ISSUE THREAD

**Issue by qy-yang** [vaexio/vaex#495]
I was trying to open a hdf5 file but got an error below:
`OSError: Could not open file: *.hdf5, did you install vaex-hdf5? Is the format supported?`

I have installed vaex via conda install and the package version I have for vaex and relevant modules are as below:
`
vaex-astro                0.6.1                      py_1    conda-forge  
vaex-core                 1.3.0            py37hb3f55d8_0    conda-forge  
vaex-hdf5                 0.5.6                      py_0    conda-forge  
vaex-jupyter              0.4.1                      py_0    conda-forge  
vaex-ml                   0.6.2                      py_0    conda-forge  
vaex-server               0.2.1                      py_0    conda-forge  
vaex-viz                  0.3.8                      py_0    conda-forge  
`
I am using Ubuntu 18.04.3 LTS and python 3.7.3.

**Comment by JovanVeljanoski** [comment]
Hi, 

can you try:

```
import vaex
df = vaex.example()
```

See if that works and let us know?

Cheers, 
J.

**Comment by qy-yang** [comment]
> Hi,
> 
> can you try:
> 
> ```
> import vaex
> df = vaex.example()
> ```
> 
> See if that works and let us know?
> 
> Cheers,
> J.

Hi Jovan,

Thanks for your prompt reply. The above codes work fine.

Cheers,
QY

**Comment by JovanVeljanoski** [comment]
Hi, 

Just a quick follow up question: the .hdf5 files you are trying to open.. were they created with vaex, or in some other way?

Cheers, 
J.

**Comment by qy-yang** [comment]
> Hi,
> 
> Just a quick follow up question: the .hdf5 files you are trying to open.. were they created with vaex, or in some other way?
> 
> Cheers,
> J.

Hi Jovan,

I created the hdf5 using pandas.HDFStore(), and the pandas version is 0.25.3.

Cheers,
QY

**Comment by JovanVeljanoski** [comment]
Ah, yes. 

So HDF5 and HDFS are different file formats, although the names are similar. This is why you can't read in your files (i.e. they are not hdf5 files).

If it helps, you can convert a pandas dataframe to vaex via `vaex_df  = vaex.from_pandas(pandas_df)` and then export it to hdf5 via `vaex_df.export_hdf5(...)`

**Comment by qy-yang** [comment]
> Ah, yes.
> 
> So HDF5 and HDFS are different file formats, although the names are similar. This is why you can't read in your files (i.e. they are not hdf5 files).
> 
> If it helps, you can convert a pandas dataframe to vaex via `vaex_df = vaex.from_pandas(pandas_df)` and then export it to hdf5 via `vaex_df.export_hdf5(...)`

Hi Jovan,

Thanks for your explanation. I am still a bit confused here. Based on the Pandas docs, the class HDFStore in Pandas is used to deal with PyTables (HDF5). Here is the docs link: https://pandas.pydata.org/pandas-docs/stable/reference/io.html#hdfstore-pytables-hdf5.

So if I understand the above Pandas docs correctly, it should generate HDF5 file instead of HDFS file which is using in Hadoop.

Cheers,
QY

**Comment by maartenbreddels** [comment]
Dear QY,

you are absolutely right, it *is* hdf5, and indeed it is using PyTables. I've never considered supporting what PyTables does, because they don't use column based storage. I've checked if that is still the case:
![image](https://user-images.githubusercontent.com/1765949/70603679-58dd6d80-1bf7-11ea-9b61-574a4ea7949b.png)

And what you can take away from this, is that the data of column x is close to column y, meaning if you only work with column x you will also waste time/resources reading in column y (since disk and CPU always works in batches).
Vaex will not support this file format natively, but it is very easy to get the data in via pandas:
```python
import vaex
pdf = pd.read_hdf("./store.h5")
vdf = vaex.from_pandas(df, copy_index=False)
```

![image](https://user-images.githubusercontent.com/1765949/70604040-241de600-1bf8-11ea-8164-7da253397094.png)

If you goal is to store the data, and you want to work with it using vaex, I recommend converting it to a vaex dataframe and exporting that to hdf5. 

Let me know if this answers your question.

Regards,

Maarten

**Comment by qy-yang** [comment]
Hi Maarten,

Thanks for your reply. That's clear to me. I should be able to close the issue in this case.

Cheers,
QY
