### ISSUE TITLE
pip install vaex error

### ISSUE THREAD

**Issue by lx1054331851** [vaexio/vaex#607]
When i use pip to install vaex, error happened as below:
![image](https://user-images.githubusercontent.com/12423206/75095455-c9c5dc00-55cf-11ea-9f5b-04a535364ab7.png)

**Comment by maartenbreddels** [comment]
Hi,

this error occurs because we don't have a binary wheel yet for windows. If you google that error, it will say you need to install visual studio c++ to compile the c extension of vaex. However, you would also need to compile/install pcre, which is non-trivial.
I recommend using conda instead, would that work for you?

regards,

Maarten

**Comment by maartenbreddels** [comment]
This should work now
