### ISSUE TITLE
Chore: run benchmarks periodically to record improvements or detect regressions

### ISSUE THREAD

**Issue by byaminov** [vaexio/vaex#620]
There are some benchmarks in Vaex that let measure performance of various functions, for example the [`benchmarks/strings.py`](https://github.com/vaexio/vaex/blob/master/benchmarks/strings.py). It would be useful if we can run those benchmarks periodically (for example, nightly) and record the results. Then when there is a performance improvement (like for example #612), a benchmark run history can show the improvement. And if a certain change would decrease the performance of certain functions, we could detect it automatically.

Let's do the following:
- [ ] Setup [airspeed velocity](https://asv.readthedocs.io/en/stable/) in the repository to let run the benchmarks. 
- [ ] `strings.py` and `from_pandas.py` can be used as the first benchmark tests.
  - [ ] Look also for other existing benchmarks in the repository.
- [ ] The benchmark results should be published as GitHub pages in the Vaex repository.
- [ ] Document the process of running a benchmark locally and developing new benchmarks.
  - as a README file in the benchmarks folder.
- [ ] Configure a physical Linux laptop to run the benchmarks every night or every week.

**Comment by maartenbreddels** [comment]
> * Setup [airspeed velocity](https://asv.readthedocs.io/en/stable/) in the repository to let run the benchmarks.

Initially I thought it should go into a separate repo, because if you write new benchmarks, you cannot run them on the old code anymore, but that is not how asv works, it checks out the old code, but runs the current benchmark code, if I am not mistaking.

> * Look also for other existing benchmarks in the repository.

I have some local uncommitted, I'll push those


> * Document the process of running a benchmark locally and developing new benchmarks

Yes, that would be great! Like what are good practices during development vs the automated tests.



Another thing which would be nice, is to have a bot post the performance impact of a PR, but I don't know how much work that is, I can imagine more people want that, but I could not find something out there that does this.

For the benchmark data, we probably want to have a few on disk datasets, like the taxi, the one for strings. Or, we create a new artificial dataset. This way the benchmark can run really fast, since making these usually takes a long time (RNG'ers can be slow).

Anyway, excited about this, this has been missing for ... ever :)

**Comment by maartenbreddels** [comment]
> * `strings.py` and `from_pandas.py` can be used as the first benchmark tests.

Btw, I don't think we need to run the pandas test, we can compare them a final time, but from there on we can just record the absolute timings, and avoid regressions that way.

I don't think this should be a benchmark against other libraries perse (although we could do that as well))

**Comment by maartenbreddels** [comment]
https://discuss.ossdata.org/t/pooling-efforts-on-continuous-benchmarking-cb/206/15 is the discussion on continuous benchmarking I was referring to during our call.
