### ISSUE TITLE
vaex version

### ISSUE THREAD

**Issue by limo1213** [vaexio/vaex#663]
No matter which version I install, 1.0.0-beta.6 will be display when I check vaex version by print(vaex.__version__). 
I try to install vaex 2.6.1 and 1.0.1 in jupyterlab.

**Comment by JovanVeljanoski** [comment]
Hi @limo1213 

Vaex is a collection of packages in the vaex framework, so to speak.  They are listed on the [front page](https://github.com/vaexio/vaex), and on the [docs page](https://docs.vaex.io/en/latest/).

So, the latest version of the vaex-meta package (which is a collection of all the individual vaex packages) is 2.6.1.

However, `vaex-core` which contains the DataFrame library, the main methods etc..  should be 1.5.0 (although now I see a bug which shows 1.1.0-beta6). 

When you check for version, you check the version of the `vaex-core` package, since everything else is dependent and attached to it, so to speak.

This kind of modularity, while might be annoying at first, is really helpful for production systems as it allows you to only install what you really need, saving in space and complexity.

You can try `pip search vaex`, or `conda search vaex -c conda-forge` and after `conda search vaex-core -c conda-forge`, from the command line, depending on what you use.

If you want to install from source and you need some help, let us know.

Hope this helps, 
J.

**Comment by limo1213** [comment]
@JovanVeljanoski Got it and thanks for your reply.
