### ISSUE TITLE
Unable to open mutliple hdf5 file using open_many

### ISSUE THREAD

**Issue by Tanay0510** [vaexio/vaex#665]
Here is the code. 

```

hdf5_list = glob.glob('/Volumes/HD-E1/HDF5/*.hdf5')
hdf5_list.sort(key=alphanum_key)
hdf5_list = np.array(hdf5_list)

master_df = vaex.open_many(hdf5_list)
master_df.export_hdf5(path='/Volumes/HD-E1/FinalHDF5/NycTaxiData.hd5', progress=True)

```

the hdf5_list has all the file in it. The whole code runs without any error but it just creates a file of 14kb. I don't know where the problem lies. I even did the ulimit to 9999

**Comment by JovanVeljanoski** [comment]
Hi @Tanay0510 

(this feels like a deja vu :) ).

Can you please remove any code that is not related to the problem you are experiencing (such as importing unrelated libraries, or definitions of functions not related to the issue).

On topic:
What happens when you try to view or interact with `master_df`. If you print it out, or view few columns, what happens? 

Can you view and interact with the individual files?

**Comment by Tanay0510** [comment]
I am just trying to get it to work. Been working on this for last 2 days. 

This is what it gives me when I print the master_df. 

"
0
1
2
3
4
...
1,179,745,844
1,179,745,845
1,179,745,846
1,179,745,847
1,179,745,848
"

When I ran the code shown below, it converted the first file to hd5.

master_df = vaex.open_many(hdf5_list[0])

 But when I am trying to do 

master_df = vaex.open_many(hdf5_list[0:84]) ## Since there is 84 files, it just gives me a file of 14kb.

**Comment by JovanVeljanoski** [comment]
So the `master_df` shows that there are many rows but no columns? 
What happens when you do `master_df.column_names`  ? 

Also can you try and open a single file (via the `vaex.open` method), and try to print it out. Do you see column data there?

Note that to use `vaex.open_many` each hdf5 file needs to have the same column names. I don't recall from the top of my head what happens if there are inconsistencies, but you might want to test this gradually: read in the 1st 10 files or so, than the next etc, until you encounter the issue, either in the data or in Vaex.

**Comment by Tanay0510** [comment]
When I do master_df.column_names, it gives {}, an empty list. 

But when I do 
master_df = vaex.open_many(hdf5_list[0])
print(master_df.column_names)

it gives the following error. 
''
ERROR:MainThread:vaex.file:could not read 4 bytes from '/'
OSError: Could not open file: /, did you install vaex-hdf5? Is the format supported?
''

When I use vaex.open, I am able to see the columns names. 

Each of the file has the same column names I guess. As I downloaded the 2009-2015 dataset.

**Comment by JovanVeljanoski** [comment]
Yes, so if there are no columns to save.. it makes sense that the output file is super small :).

`vaex.open_many` takes a list of strings, and you are giving it a single string in your above example.

If you are trying to get the taxi data converted form the CSV files to a single HDF5, note that the CSV data is dirty: when I did it I had to do a LOT of manual changes/fixes to the CSV data before I could read it consistently into a table with pandas or vaex. It is not something you can plug and play. Good luck! :)

**Comment by Tanay0510** [comment]
Can you tell me what changes you had to do? 

I encountered some files that had three commas ,,,, instead of ,,  and I changed that to proper format. 

I don't know where to look for it. Any help would be great. Just show me the way and I will figure it out on my own.

**Comment by JovanVeljanoski** [comment]
I have not record of the exact changes: i did this well over a year ago. I remember there were many inconsistencies. I had to do type checks, counts checks for every CSV file making sure they were consistent.  I remember I had to do things manually quite a bit, since it was not 1-2 types of changes, but various. 

Maybe if you google more extensively you will find something... but I am sorry I can't help further with this. It is not a vaex issue tho, just the data is dirty.
