### ISSUE TITLE
Bridging exports and imports between dask and vaex

### ISSUE THREAD

**Issue by alexmascension** [vaexio/vaex#702]
I posted this as a quesiton in StackOverflow. Feel free to flag it as required.
https://stackoverflow.com/questions/61467527/bridging-exports-and-imports-between-dask-and-vaex

I am working jointly with vaex and dask for some analysis. In the first part of the analysis I do some processing with dask.dataframe, and my intention is to export the dataframe I computed into something vaex reads. I want to export the data into a memory-mappable format, like hdf or arrow.

dask allows exports into hdf and parquet files. Vaex allows imports as hdf and arrow. Both allow exports and imports as csv files, but I want to avoid that.

So far I got the following options (and problems):
* If I export into an hdf5 file, since dask exports the file in a row format, but vaex reads it in a column format, the file cannot be imported (https://vaex.readthedocs.io/en/latest/faq.html).
* I can export the data into parquet files, but I don't know how to read them from vaex. I've seen some answer in SO that transforms the files into an arrow table, but this requires the table to be loaded into memory, which I can't because the table is too large to fit into memory.

I can of course do an export into a csv and load it in chunks into vaex, then export it into a column-format hdf, but I don't think that should be the purpose of two modules for big objects.

Is there any option I am missing and that would be compatible to "bridge" the two modules without either loading the full table into memory, or having to read/write the dataset twice?

**Comment by JovanVeljanoski** [comment]
Hi @alexmascension 

Thanks for reaching out. Interesting problem, we've never met this use-case before. I think it should be easy enough to export the data into arrow or (vaex-friendly) hdf5 like this:

Create a loop that will go over the entire dask dataframe in chunks that can fit in memory. Convert those chunks to a regular pandas dataframe, vaex can read any pandas dataframe, and than you can export that into hdf5 or arrow. A pseudo code would be something like this:
```
chunk_size = 10_000_000  # for example
n_chunks = np.int(np.ceil(len(ddf) / chunk_size))

for i in range(n_chunks):
    index_min = i * chunk_size
    index_max = index_min + chunk_size
    pandas_df = ddf.loc[index_min: index_max].compute()
    vaex_df = vaex.from_pandas(pandas_df, copy_index=False)    # See what is suitable for the copy index arg in your case
    vaex_df.export(f'my_file_{i}.hdf5')  # or .arrow
```

The above idea relies on your dask dataframe having a unique index from 0:N_rows since dask is not so friendly about slicing. 

After you have the multiple files, you can simply do 

```
master_df = vaex.open('my_file_*.hdf5')
```
And you will get a single dataframe which is a concatenation of all the individual files.
You can also use 
```
master_df = vaex.open_many([list_of_file_names])
```

I looked at the SO question and answers: you can also export to parquet and read parquet with vaex. However (for the moment) vaex does not read parquet files in an out-of-core manner, so you may run into memory issues. This is an area we are looking to improve in the near future. 

Finally, out of curiosity (but also so that we can improve vaex), can you please tell us what is the raw format of the data you are using, and what kind of operations you are using dask.dataframe for? Is it something that vaex can not do? Or vice-versa, what is your motivation of using vaex following dask.dataframe operations?

I hope this helps!
J.

**Comment by alexmascension** [comment]
Hi Jovan, 

Thanks for your help first! 

I've prepared a notebook with a parallelized option based on your idea to make it faster. I take the partitions directly, which makes it easier (I guess, or at least it feels more intuitive to me) to divide and save.

https://www.kaggle.com/alexmartnezascensin/playing-around-with-nyc-data

As for the operations and format, I took simply the NYC taxi dataset (2017 - 2019 due to column changes, January only to fit the data, although in local I have the rest of months, yellow / green)  in csv from the original website and I did some formatting of the columns. 

Basically I want to rename columns / merge / add new columns to the dataset. I am not really sure if the code I used for dask works, or if it has functions of, in vaex. In reality, I wanted to use dask to learn a bit of it, and also use vaex, mainly for representation. Although I'm sure I'll end up using it to do data transformation. 

This surely is not the last version because I'll have to do some formatting / data type correction, because there is some lack of overlap between the dask dataframe and the vaex dataframe. I'll work on that during the weekend if I'm able to.

I hope this answers your questions. Don't hesitate to ask for more if needed! 
Also, regarding the issue, since your solution is quite straightforward, I don't know if more improvement has to be done, and if the issue has to remain open. The ideal case would be to create a function for that, but given that I'm the only case (so far), it might not be necessary at all.
