### ISSUE TITLE
groupby funcation missing

### ISSUE THREAD

**Issue by qiruoqiqi77** [vaexio/vaex#745]
```
date = np.array(['2015-01-01', '2015-02-01', '2015-02-01', '2015-02-01', '2015-01-01'])
y = np.arange(len(date))
df = vaex.from_arrays(date=date, y=y)
```

if df is pandas DataFrame ,we can write the code to do this:
```
for key,value in df.groupby(['date']):   
    print(key)
    print(values)
```

but when df is vaex dataframe, we don't achieve this step,can vaex realize this function?

thank you!

**Comment by qiruoqiqi77** [comment]
At present, we convert vaex dataframe to pandas dataframe, but the amount of data is too large, so we still hope to achieve it through vaex.

**Comment by maartenbreddels** [comment]
Hi,

We have this functionality in this branch: https://github.com/vaexio/vaex/pull/383 but that never went into master or a release.

Could you explain what you want to go with each dataframe? Because we could add this functionality to vaex, but I think for almost all uses cases there must be more efficient ways of doing this. For instance, if you want to do another aggregation per dataframe, it would be better to do this aggregation in one go.

Maybe if you can provide an example of what you'd like to do with each dataframe, we can see if we can find an alternative (more efficient) way of getting your results.

Regards,

Maarten

**Comment by serega-upgini** [comment]
@maartenbreddels one of use-cases:
- Group by key
- find one or more records from a group by criteria

business cases:
- Group by userId and get the most recent event
- Group by userId and  get the most recent and the oldest events.

**Comment by JovanVeljanoski** [comment]
This is now possible, so closing this. Thanks!
