### ISSUE TITLE
Virtual column and np.fromstring

### ISSUE THREAD

**Issue by druzmieres** [vaexio/vaex#785]
Hi,

I have a CSV file containing a column with data that looks like `(num1, num2, num3, etc.)`. If I read this file with pandas, I can convert the values in the column to numpy arrays like this: `df[column].apply(lambda x: np.fromstring(x[1:-1], sep=','))`.

I read the documentation and found out about "virtual columns". The example is this one:
```
df['r'] = np.sqrt(df.x**2 + df.y**2 + df.z**2)
df[['x', 'y', 'z', 'r']]
```
So I assumed I could do the following to replicate what I do with pandas, but it didn't work:
`df['new_column'] = np.fromstring(df.column[1:-1], sep=',')`. The error I get is `TypeError: a bytes-like object is required, not 'Expression'`.

Then, I tried extending vaex:
```
@vaex.register_function()
def fromstring(arr):
    return np.fromstring(arr[1:-1], sep=',')`
```
And to call the method: `df['new_column'] = df.func.fromstring(df.column)`. If I want to see the values of the new column, I get `DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.` However, I don't get this error with pandas.

Is it possible to do what I need? Is there an error in what I've tried so far?

The versions I'm using are:
```
numpy==1.18.4
pandas==1.0.4
vaex==3.0.0
```

Thanks!

**Comment by druzmieres** [comment]
Nevermind, I got it. 
```
def fromstring(column):
    return np.fromstring(column[1:-1], sep=',')

df['new_column'] = df.apply(fromstring, arguments=[df.column])
```

**Comment by JovanVeljanoski** [comment]
Hi @druzmieres 

Thanks for reaching out! 

Yes, you are right, you can always use `apply`, although we try to avoid it and use it only as a last resort since it is not very efficient. 

I am sorry but I have a little trouble understanding your use-case. Maybe if we understand it better, we can try and implement or suggest a solution that would work better than apply. 

So If I understand correctly, you have a column which is a string, and has and looks something like 
`'5, 8, 10, .... 12`. Then you want to use `np.fromstring` to essentially convert that strong into a numpy array of numbers, and then take a specific element from it? Or would you like the sample to consist of a list/array of numbers? 

If it is possible, can you please send a minimal mock data example so we can try this out locally?

Also, yes you are right, vaex does understand many (most?) of the numpy methods, especially the algebraic ones, but not all are understood/implemented yet (as is the case with `np.fromstring`).

Thanks!

**Comment by druzmieres** [comment]
Hi,

This is a CSV sample:
```
A,B
2.3,"(2.46,4.42)"
2.2,"(3.24,1.72)"
```
The file comes from an external service, so I can't just generate it in a different way. Column A contains floats, column B contains strings (which are really arrays of floats) that I want to work with. Therefore, the first step is to convert these strings to arrays (particularly, numpy arrays).

Is this information enough?

Thanks!

**Comment by JovanVeljanoski** [comment]
Hi, 

Yes, that is enough information thank you. I understand the problem.

Right now vaex does not support adding 'matrices' into the dataframe, but single columns only. Also it does not (officially) support nested structures like lists/dicts/arrays, since we can't persist them to disk (yet). 

We are working on better integration with Arrow, so than all of these things will be easier. 

So for now (unfortunately) apply is the best option. We are trying to use apply as little as possile, since it is not easy to parallelise, but provide methods that can be used to solve common usecases when possible. 

I'll keep this in mind as we move forward.
Thank you!
