### ISSUE TITLE
Datetime floor

### ISSUE THREAD

**Issue by Nishant23** [vaexio/vaex#842]
In pandas, we can do something like this

`df['Time] = df['Time'].dt.floor('10ms')`

The output is floor of the time column in 10ms roundoff.

Can we do similar in vaex dataframe?

**Comment by JovanVeljanoski** [comment]
Hi @Nishant23 

We don't have that yet, but no reason not to add it i guess. So I've just opened a PR adding this functionality. It is basically done, just a subject to review. 

If you are comfortable doing dev install, you can try the PR branch right away, otherwise we are likely to release an incremental update of vaex very soon.

Cheers,
J.

**Comment by Nishant23** [comment]
@JovanVeljanoski I'll use dev install, can you point me the branch which should I use?

**Comment by JovanVeljanoski** [comment]
Closed via #843
