### ISSUE TITLE
OSError: Could not open file:***, did you install vaex-hdf5? Is the format supported?

### ISSUE THREAD

**Issue by yuba316** [vaexio/vaex#847]
I was trying to open a hdf5 file with vaex.open(XXX.hdf5), and this OSError happened.
**OSError: Could not open file:XXX, did you install vaex-hdf5? Is the format supported?**
But I have already finished the installation through pip install vaex. Here are the version details:
vaex                          3.0.0              
vaex-arrow                    0.5.1              
vaex-astro                    0.7.0              
vaex-core                     2.0.3              
vaex-hdf5                     0.6.0              
vaex-jupyter                  0.5.2              
vaex-ml                       0.9.0              
vaex-server                   0.3.1              
vaex-viz                      0.4.0

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for reaching out. 
Can you tell us how you created the hdf5 file? Was it created with vaex, pandas or in another way. 
It would help to know the process that went into creating the file.

Cheers

**Comment by xinnyuann** [comment]
Hi Jovan, thanks for your reply. I got the exactly same error with same version of vaex as above. I created the hdf5 file from a arrow file. With **vaex.open()**, I read the arrow file, then with **vaex.export_hdf5()**, I created this hdf5 file. Can you help look into this?

**Comment by maartenbreddels** [comment]
Could you create 1 row file, and share it here so I can test it?

**Comment by xinnyuann** [comment]
Thank you for the prompt reply @maartenbreddels, I'm able to read the hdf5 file created by vaex.export_hdf5 now, but once I filtered my vaex dataframe, I got error like this: `ValueError: Array is of length 1264222, while the length of the DataFrame is 1264222 due to the filtering, the (unfiltered) length is 1524038.` Guess it's not related to this git issue anymore.

**Comment by maartenbreddels** [comment]
Hi Xin,

That issue is specific for arrow files, but you are using hdf5 right?
Is this error occurring when reading/opening, or later on? Maybe it helps if you share some code.

Regards,

Maarten

**Comment by xinnyuann** [comment]
Hi @maartenbreddels Yes, I was using hdf5 file, created from arrow file with vaex.export_hdf5(). Here's some code to reproduce the error - `Array is of length %s, while the length of the DataFrame is %s due to the filtering, the (unfiltered) length is %s.` 

**>>> df = vaex.open("sample.hdf5")
>>> df.count()**
array(88102549)
**>>> filter_df = df[df.sales_date == '2020-07-25']**
**>>> filter_df.count()**
array(1149743)
**>>> filter_df['sales_date_dt'] = filter_df.sales_date.values.astype('datetime64[ns]')**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dde_user/.local/share/virtualenvs/Xin-gykj_A9E/lib/python3.6/site-packages/vaex/dataframe.py", line 4498, in __setitem__
    self.add_column(name, value)
  File "/home/dde_user/.local/share/virtualenvs/Xin-gykj_A9E/lib/python3.6/site-packages/vaex/dataframe.py", line 6053, in add_column
    super(DataFrameArrays, self).add_column(name, data, dtype=dtype)
  File "/home/dde_user/.local/share/virtualenvs/Xin-gykj_A9E/lib/python3.6/site-packages/vaex/dataframe.py", line 2941, in add_column
    raise ValueError("Array is of length %s, while the length of the DataFrame is %s due to the filtering, the (unfiltered) length is %s." % (len(ar), len(self), self.length_unfiltered()))
ValueError: Array is of length 1149743, while the length of the DataFrame is 1149743 due to the filtering, the (unfiltered) length is 88102549.

**Comment by maartenbreddels** [comment]
Hi Xin,

please be more clear next time when you describe the problem, you said "but once I filtered my vaex dataframe, I got error like this". While your code you shared shows the error when adding the column.
This issue is described/explained many times on this GitHub issue, so it's a clear stumbling block, so we added this to the FAQ:
https://docs.vaex.io/en/latest/faq.html#Why-can't-I-add-a-new-column-after-filtering-a-vaex-DataFrame?
Although we should maybe add the text of the error msg there, so it's more Google-friendly (cc @JovanVeljanoski ).
Hope this helps your problem!

Regards,

Maarten

**Comment by xinnyuann** [comment]
Thank you so much for your help!
