### ISSUE TITLE
Knn support -Vaex-ml

### ISSUE THREAD

**Issue by Vibha111094** [vaexio/vaex#891]
Does Vaex-ml provide knn support?

**Comment by JovanVeljanoski** [comment]
Hi, 

Vaex-ml itself does not implement a kNN. However we do provide an (experimental) binding to [annoy](https://github.com/spotify/annoy).

You need to install annoy yourself, and than access it via
```
from vaex.ml.incubator import annoy
knn = annoy.ANNOYModel(...)
```

We were potentially looking to include a wraper for Google's [scann](https://github.com/google-research/google-research/tree/master/scann), but currently there is not licence associated, and the installation is not straightforward. Perhaps in time. 

If you know of a good out-of-core kNN algorithm that you might find useful, please let us know. 

Btw, what is the size of your dataset. I have found `scikit-learn`'s kNN to be quite good and fast, if you can fit it all in memory.

**Comment by JovanVeljanoski** [comment]
You can also look at https://scikit-multiflow.github.io/ 
they seem to have implementations of kNN that can work in patches or per sample (online) which should be compatible with the incremental predictor in vaex.ml

I will close this since we do not have any immediate plans to implement a kNN ourselves. Thanks!
