### ISSUE TITLE
Random Forest/Gradient Boosting on a very large dataset

### ISSUE THREAD

**Issue by Fatima-Zahra96** [vaexio/vaex#903]
I want to apply a RandomForestClassifier and a GradientBoostingClassifier on very large datasets (columns=1091, rows=2 585 674), but it uses a lot of memory and CPU. How can I do it with vaex ?

**Comment by JovanVeljanoski** [comment]
Hi, 

Vaex does not provide implementation any specific predictive models.  We only have our own KMeans algorithm.

Having said that, I can suggest few options. They may, or may not be relevant to you based on your data and specific problem:
 - use `catboost` to train multiple models on subsets of your data, and than sum those to create a single master model ([the catboost docs](https://catboost.ai/docs/concepts/cli-sum-models.html)). This [is documented here](https://vaex.readthedocs.io/en/latest/tutorial_ml.html#CatBoost-example). Note that this is not released yet, so you will need to install vaex from source if you want to use the wrapper. Otherwise you can probably do this your self manually - just pass subsets of data to different catboost models, and then sum them up (refer to their documentation). If you are interested in this approach, it would be [good to read this](https://github.com/catboost/catboost/issues/1344).

- use a 'online/incremental' model, scikit-learn supports few, you can also look at scikit-multiflow.

**Comment by Fatima-Zahra96** [comment]
Hi,
Thank you for your reply, 

1. about the second point i used the 'online/incremental' models before and it worked amazingly well :) 
2. about the first point, I need to learn more about **catboost** and the **sum_models** method and I will see if it will work with my dataset 

Thank you very much for your help !

**Comment by JovanVeljanoski** [comment]
We have an example on using vaex with incremental models. Maybe you've seen in already. 
[Here is the link](https://towardsdatascience.com/ml-impossible-train-a-1-billion-sample-model-in-20-minutes-with-vaex-and-scikit-learn-on-your-9e2968e6f385).

Good luck!

**Comment by Fatima-Zahra96** [comment]
Thank you very much 😄 !
