### ISSUE TITLE
Vaex challenges with big files

### ISSUE THREAD

**Issue by NarayanB** [vaexio/vaex#913]
Hi,
We are evaluating Vaex as a part of our POC to process daily csv files to arrow. While it works for 
smaller files, we have challenges creating a single consolidated .arrow or .hdf5 file. In general it looks
like opening a single arrow file is faster than a single hdf5 file. So the preference is to process daily csv files
and convert them to .arrow files and then use PyArrow to open all the .arrow files. This will give a consolidate .arrow file that can be written to disk. We get consolidated pandas from the arrow files. The export is done by vaex's from_pandas with copy_index=False.

But then opening the single consolidated arrow file poses challenges as the file size grows, like 50Gb or 
so with like 100 million rows. The error thrown is - array is of length %s, while the length of the Dataframe is %s. For example, the array length is 50743164 and Dataframe length is 83577265. 

Other options like 
(a) vaex.open_many on multiple arrow files takes lot of time, which complicates server restart process
(b) vaex.open a consolidated parquet doesn't work
(c) vaex.open with arrow file written using pyarrow RecordBatchFileWriter throws the error - Invalid flatbuffers message.	This again seems to happen for a big arrow file with 100+ million rows

The faq section mentions of creating hdf5 from vaex open_csv but we use other libraries for open_csv. 

As we need to append to previous day consolidated arrow file, performing daily export is an expensive process. Are there any other recommended ways to append the delta arrow to the original .arrow file ?

Also, vaex.open holds reference to the memory mapped file and so rewriting the same .arrow file is not allowed by OS. This issue can be circumvented by other ways but still doesn't give an option to append a delta arrow to the previous .arrow file

Please suggest if the above issues are slated for vaex-4.0 release. Appreciate your time and valuable input to these issues.

**Comment by JovanVeljanoski** [comment]
Hi @NarayanB 

Thanks for your interest in vaex. 

What you are describing is a common scenario, one we are trying to address. Let me briefly describe one approach we are likely to take. Arrow files support chunking, meaning that a single arrow file can contain multiple tables of the same schema. Opening such a file with vaex will result in a single DataFrame containing the data of all individual tables. 

Opening a chunked arrow file is not possible in the latest released version - which is why I think the error you mentioned shows up. I believe it is however supported in master, so if you want to try this out, you can try installing vaex from source. 

As for adding new portions of data to the big arrow file, it should be possible to append a new chunk of data to the same big arrow file. This is not available right now, but a feature we are looking to support soon. I believe it to be exactly what you are looking for.

So the envisioned work-flow would be something like:
 - day 0: parse raw CSV with pandas/vaex, then export to .arrow
 - day 1: parse raw  CSV with panas/vaex, then export to arrow but append as a new chunk (or table, not sure what the right terminology is) to the file created on day 0
 - day 2 and on: repeat. 

Than whenever the analysis needs to run, you just need to open the original .arrow file. Does this sound good to you?

Some other notes regarding your post above:
 - opening an arrow file and hdf5 file should be equally as fast. Both are memory mappable, so there is no "opening" going on what so ever. If you can show that there is some performance difference, we should be very interested to see it!
 - At the moment, opening a Parquet file is done in memory. We hope to be able to memory-map and lazily read a parquet file at some point in the future, but for now it will stay as it is.
- To be sure that vaex can open a certain type of file, please use vaex to export to file, be it Arrow or HDF5 At least for now, until we have a better integration with Arrow. As said earlier, if the Arrow file contains chunks, the released version of vaex will not be able to read it, but the latest master might/should. 
- "Opening" a memory mappable file with vaex does not at all depend on the file size, or number or rows. It should be the same for 10 rows or 10 billion rows (for a single file!). 
- A question: how many columns does your data have? In principle, `vaex.open(my_file_*.arrow)` or `vaex.open_many([my_file_1.arrow, my_file_2.arrow.....my_file_n.arrow])` might work, but at the moment we suffer from a rather large performance penalty when there are many columns (~50, or 100 or more). We also hope to address this soon.
I have personally used `vaex.open_many([...])` with 1000s of files, but each had ~25-30 columns or so. I agree that, at least right now, is perhaps not the ideal way to proceed, if you want to run any sort of analysis daily. 

If I may ask (out of general curiosity), what is the domain on your work? I am always curious on what  & how people use vaex. It also helps us to think on how to improve it. 

I hope this helps a bit, 
Jovan.

P.S.: If you are happy with vaex and would like commercial support, please contact us at contact@vaex.io.

**Comment by NarayanB** [comment]
> 
> 
> Hi @NarayanB
> 
> Thanks for your interest in vaex.
> 
> What you are describing is a common scenario, one we are trying to address. Let me briefly describe one approach we are likely to take. Arrow files support chunking, meaning that a single arrow file can contain multiple tables of the same schema. Opening such a file with vaex will result in a single DataFrame containing the data of all individual tables.
> 
> Opening a chunked arrow file is not possible in the latest released version - which is why I think the error you mentioned shows up. I believe it is however supported in master, so if you want to try this out, you can try installing vaex from source.
> 
> As for adding new portions of data to the big arrow file, it should be possible to append a new chunk of data to the same big arrow file. This is not available right now, but a feature we are looking to support soon. I believe it to be exactly what you are looking for.
> 
> So the envisioned work-flow would be something like:
> 
>     * day 0: parse raw CSV with pandas/vaex, then export to .arrow
> 
>     * day 1: parse raw  CSV with panas/vaex, then export to arrow but append as a new chunk (or table, not sure what the right terminology is) to the file created on day 0
> 
>     * day 2 and on: repeat.
> 
> 
> Than whenever the analysis needs to run, you just need to open the original .arrow file. Does this sound good to you?
> 
> Some other notes regarding your post above:
> 
>     * opening an arrow file and hdf5 file should be equally as fast. Both are memory mappable, so there is no "opening" going on what so ever. If you can show that there is some performance difference, we should be very interested to see it!
> 
>     * At the moment, opening a Parquet file is done in memory. We hope to be able to memory-map and lazily read a parquet file at some point in the future, but for now it will stay as it is.
> 
>     * To be sure that vaex can open a certain type of file, please use vaex to export to file, be it Arrow or HDF5 At least for now, until we have a better integration with Arrow. As said earlier, if the Arrow file contains chunks, the released version of vaex will not be able to read it, but the latest master might/should.
> 
>     * "Opening" a memory mappable file with vaex does not at all depend on the file size, or number or rows. It should be the same for 10 rows or 10 billion rows (for a single file!).
> 
>     * A question: how many columns does your data have? In principle, `vaex.open(my_file_*.arrow)` or `vaex.open_many([my_file_1.arrow, my_file_2.arrow.....my_file_n.arrow])` might work, but at the moment we suffer from a rather large performance penalty when there are many columns (~50, or 100 or more). We also hope to address this soon.
>       I have personally used `vaex.open_many([...])` with 1000s of files, but each had ~25-30 columns or so. I agree that, at least right now, is perhaps not the ideal way to proceed, if you want to run any sort of analysis daily.
> 
> 
> If I may ask (out of general curiosity), what is the domain on your work? I am always curious on what & how people use vaex. It also helps us to think on how to improve it.
> 
> I hope this helps a bit,
> Jovan.
Hi Jovan,
Thanks for your quick response. Let me try the append approach suggested by you. In general, i was successful in using pyarrow to read all arrow as a single table.

(1) Opening a single arrow file or hdf5 file exported from vaex has millisec difference. But when you do filter operations on a big dataset, i saw that arrow was faster.
(2) Yes, the issue i mentioned to open/operate arrow file had > 50 columns.  Small correction, i can open the arrow file, when i do any filter then i get the error - array is of length %s, while the length of the Dataframe is %s. For example, the array length is %s and Dataframe length is %s
(3) Getting vaex from pandas is a no brainer, but it takes around 10 minutes for a df with 100 million rows. Using this option during server start will bring in delays
(4) In general, i feel that Pyarrow's recordbatchfilewriter option is very fast to write out arrow file. I tried to write a single arrow file from all the independent arrow files, but vaex open throws - Invalid flatbuffers message. My suggestion would be to make it easy to open arrow file of any size seamless. That means either open_many(file list) or a single open. 
(5) Is there a difference between df exported using export_arrow vs export_hdf5. I had some success with opening a single hdf5 from export_hdf5, but the filter operations are taking 2-3 seconds for some queries. Not sure if single arrow file would take the same time. I read in the forum about some slowness with isin filter. 
(6) I see that export_hdf5 is taking lesser time than export_arrow. Maybe export_hdf5 has some chunking or multi threading?
(7) Due to restrictions at workplace, there is no option for me to try the master branch. So, I will have it wait for the new release

I work for a major financial bank. 

Regards,
Narayan

**Comment by JovanVeljanoski** [comment]
Hi, 

So the proposed workflow is not yet implemented fully, but that is the direction we are leaning towards. I hope it will be part of the next release. 

On the points you raised:

1) That is quite strange. There should not be any difference what so ever. In the past, in fact it was hdf5 that was more performant. I would like to test this if possible. Can you please give me a description of the data. Nothing specific, but like number of columns, how many are of each data type, and the number of rows. Perhaps the type of query / filter would be helpful - just in generic terms. 

2) That is strange indeed. Can you please provide some description in how the file is created? If an arrow file, I guess you created it with pyarrrow rather than with vaex? This could be solved in master perhaps.. 

3) What is the data format you  are reading in? We recommend pandas only when reading a non-memory mappable file (like CSV, ascii etc..). If you have an arrow or hdf5 file, you should use vaex directly, otherwise you are missing half of the benefit of vaex (the memory mapping). 

4) At least for now (we are working on better integration with arrow so this should not be an issue in the future), it is best to export via vaex - to guarantee that the data will work. 

5) I guess depending on the query and the number of rows you have. The file format (arrow or hdf5) should not matter at all. If it does, maybe it points to a performance issue of vaex that we might like to address. Is it possible for you to share the type of queries you do and the size of the data (generic things like `df_filter = df[(df.a > 5) & (df.text == 'word')]`, so we get an idea of where any performance issue might appear). 2-3 seconds per query might be very slow or very fast, depending on the query and the amount of data :) (and the hardware you are running on I guess - I assume you had an SSD?). 

6) Not sure about the performance of the export @maartenbreddels will know more. At least at the moment (the currently released version), there is a size limit on how large the exported arrow file can be (roughly related to available RAM I think), while this does not apply to hdf5. 

Cheers, 
J.

**Comment by NarayanB** [comment]
Hi,
(1) I created a single file of arrow and hdf5 from vaex df which had like 5 mil rows and > 50 columns. You could then see differences in open and query times
(2) Yes, arrow was created with pyarrow
(3) Agreed, but this is the other option i have with the issues that i have currently.
(4) Got it. Any timeframe for the upcoming release ? It will be helpful to know
(5) In general create a df with say 50 mil rows with > 50 columns. Create a filter on several columns and perform a group by. Now do the same except that there is just one filter clause and group. It will take around 2-3 secs. This doesn't seem the case with around 30 million rows df with 10-15 columns
(6) ok. Also, the size of hdf5 file is bigger than arrow file. Is that expected ?

Thanks,
Narayan

**Comment by JovanVeljanoski** [comment]
Hi, 

1) Something seems off there, there should not be any difference. I also tested this today, I got no difference what so ever. 
2) Ultimately it should not matter, but until the next release, try using `vaex.export_arrow(...)`.
4) No idea. It is unfunded work, so hard to estimate when we will have time to finish everything we have planned. 
5) Please share the generic queries you are doing. 2-3 seconds does not look bad at all to me for all that.. but really depends on your queries, and your hardware. 
6) Well. the more data you have the longer it takes for something to execute..

**Comment by maartenbreddels** [comment]
> (c) vaex.open with arrow file written using pyarrow RecordBatchFileWriter throws the error - Invalid flatbuffers message. This again seems to happen for a big arrow file with 100+ million rows

I think this might be related to:
https://github.com/vaexio/vaex/pull/809

> (2) Yes, the issue i mentioned to open/operate arrow file had > 50 columns. Small correction, i can open the arrow file, when i do any filter then i get the error - array is of length %s, while the length of the Dataframe is %s. For example, the array length is %s and Dataframe length is %s

My guess is that this is fixed in master.



> (6) I see that export_hdf5 is taking lesser time than export_arrow. Maybe export_hdf5 has some chunking or multi threading?

Yes, the current arrow exporter is pretty dumb, with the next version having much better arrow support (chucked arrays), we can also make use of the chuncked arrays in that part, which will speed things up a bit I think.

**Comment by JovanVeljanoski** [comment]
Closed this as out of date. Many of the topics discussed have now been implemented in master & released.

Thanks!
