### ISSUE TITLE
[BUG-REPORT]Issue importing from sql to vaex

### ISSUE THREAD

**Issue by krkakade** [vaexio/vaex#943]
Below code is from the documentation 

pandas_df = pd.read_sql_query('SELECT * FROM MYTABLE', con=engine)
df = vaex.from_pandas(pandas_df, copy_index=False)

**Description**

I have data more than RAM.
But, when I use above code, it try and pull all data in panda dataframe.
So to solve this I used chunksize attribute which  gives a generator.

To convert from generator to pandas dataframe again it is needs memory.
Below is the code I tried.

import vaex
df = pd.read_sql_query('select * from "user"."table"', conn, chunksize=1000000)
chunk_list = []
for i in df:
    chunk_list.append(i)
    data = pd.concat(chunk_list)
    df2 = vaex.from_pandas(data)
    alldat=df2.concat(df2)

Please help me with this issue.
 

**Software information**
 
 - Vaex was installed via: conda-forge  
 - OS: Windows

**Additional information**

**Comment by JovanVeljanoski** [comment]
There is not bug or issue with vaex here right?

The thing you want to do store each chunk as an hdf5 file, than open then all-together as a single dataframe. Something like (untested code). This is the generally recommended pattern:
```
import vaex
df = pd.read_sql_query('select * from "user"."table"', conn, chunksize=1000000)
i = 1
for chunk in df:
    df_chunk = vaex.from_pandas(chunk)
    df_chunk.export(f'part{i}.hdf5')
    i = i + 1

df_full = vaex.open('part*.hdf5')
# For extra performance
df_full.export_hdf5('full_data.hdf5')
df_full = vaex.open('full_data.hdf5')
```

This has been discussed in some detail elsewhere in the Issue board, so you may want to search a bit if you want more info on this, but I hope this will be enough to get you going!

**Comment by krkakade** [comment]
Thank you so much for such fast reply with a solution.
I will try this tomorrow.

I thought it is a bug because as per documentation below code should work for data with any number of records. 

df = vaex.from_pandas(pd.read_sql_query('SELECT * FROM MYTABLE', con=engine), copy_index=False)

But, it does not work. Maybe Vaex should have another feature which can pull data from generator object.
Vaex is made for pulling large data and pandas pull it in the form of generator. So, I feel there is gap between 
output of read_sql_query and input to vaex.from_pandas.

Can we put such problem in Bug-Report ?? Let me know so that I can close this issue.

**Comment by JovanVeljanoski** [comment]
> I thought it is a bug because as per documentation below code should work for data with any number of records.
Where did you read that?

The line of code you wrote fails because pandas can not hold in memory the amount of data you are trying to query from your sql database. `vaex.from_pandas` just takes over that in-memory structure. 

The power of vaex when dealing with large data is reading straight from disk, provided the data is in memory-mappable file format (arrow, hdf5). If the data is in another format, it needs to be converted. Or if the data is small enough, you can it is in memory, by taking over pandas dataframe for example, and get some performance bonuses for various operations. 

Regarding generators, I basically wrote the solution above right? We've already done this for some common cases like converting a very large CSV that does not fit into ram. You if you want, you can try and contribute a similar wrapper for an sql database.. but given the flavour of sql dialects, we though it is best to be custom for now.. 

So right now, I don't see any issue related with vaex here..
