### ISSUE TITLE
Select dataframe using boolean string condition

### ISSUE THREAD

**Issue by chitochat** [vaexio/vaex#962]
Hi,

I am trying to filter a dataframe using a string condition:

df_vx_filtered = df_vx[df_vx.x == 'abc']

The calculation doesn´t end for me (35k rows). Online I can only find numeric conditions like df.x > 2.
Thanks!

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you please go back and use the template? Or just answer all the questions the template is asking, vaex version, OS, etc..

What you describe works well, and we've tested it on a billion rows..

For local testing you can try
```
import vaex
import vaex.ml

df = vaex.ml.datasets.load_titanic()
df_filtered = df[df.sex == 'female']
df_filtered
```
In your example.. the 'x' column needs to be a of string type. If you are using the `vaex.example` dataset, of course it will not work because 'x' is a float...

**Comment by chitochat** [comment]
Hi Jovan,

Thanks for responding promptly. Apologies I am new here and can´t find the template to make sure I enter correctly. Can you point me to it?

Running on OS: Windows 10
IDE: PyCharm 2019.3.2
vaex: 3.0.0
Python: 3.8.5

I took the code you shared and modified it to run:
import vaex
import vaex.ml

df = vaex.ml.datasets.load_titanic()
df_filtered = df[df.sex == 'female']
print(len(df))
print(len(df_filtered))

The first print returns: 1309
Second print doesn´t return a result

I am obviously screwing up smth basic, but can´t see why a filtered df wouldn´t return a result when asked...

Thanks a lot,
Abhi

**Comment by JovanVeljanoski** [comment]
Ah, 

Vaex is officially not supported for Python 3.8.x on Windows.. Please try an environment with Python 3.7.x or 3.6.x.

**Comment by chitochat** [comment]
Thanks a lot. Changed and it worked!
