### ISSUE TITLE
[mental model question] - No `axis` support for row-wise calculations in `mean`?

### ISSUE THREAD

**Issue by ianozsvald** [vaexio/vaex#968]
Hello to the devs. I have a "mental model" question as I'm trying Vaex from Pandas. I've read the 11 minute Introduction and the FAQ, checked past Issues and read through parts of the API documentation and I'm probably being dense. If there's a better place to ask such questions than here then I'm happy to be pointed in a new direction.

Q1: I don't see an equivalent to a Pandas `df.mean(axis=1)` for row-wise operations. Is it more normal to think of Vaex as being column-operation only? Am I missing something? My goal is to take a large rectangular matrix e.g. customers by weeks and to calculate some statistics (all fake for now to get my head around things).

```
# 10k customers by 52 weeks
arr = np.random.random(size=(10_000, 52))
df = pd.DataFrame(arr) # start with a Pandas DataFrame
# Do a column name conversion to avoid:
# could not convert column 0, error: TypeError("'int' object is not subscriptable"), will try to convert it to string
# Giving up column 0, error: TypeError("'int' object is not subscriptable")
df.columns = [str(c) for c in df.columns]
dfv = vaex.from_pandas(df) # fraction of a second
# can't calculate "dfv.mean(axis=1)" for 52 weeks
# calculate mean for a specified column, not what I want but what I can do
dfv.mean('0') # mean of all customers for week 0
# calculate means for all columns (is there a simpler way?)
dfv.mean(list(dfv.columns.keys())) 
```

If I make a Vaex DataFrame with (52, 10_1000) items then I can do the column-wise `mean` but it takes a long time to convert the DataFrame from Pandas to Vaex and the column-wise calculations take a while. 

```
arr = np.random.random(size=(52, 10_000))
...#same code
dfv = vaex.from_pandas(df) # takes 42 seconds
...
dfv.mean(list(dfv.columns.keys())) # took too long
```

Q2: It looks like building a Vaex DataFrame from Pandas is quick for a few long columns but slow for many short columns - is Vaex setup to work on fewer longer columns?

Q3: Calculating the column-wise mean on a 10_000 x 52 matrix is fast but doing the same on a 52 x 10_000 matrix is slow - what's going on with the architecture (or my mangling of things?) to make the speed difference so big?

Q4: I don't see a Transpose (Pandas `.T`) operation, I'm guessing we're not expected to want to turn our matrix around? I appreciate that this might be a "Pandas centric" question (in part I ask because I know that Modin makes a point of how it _can_ scale a transpose to be far larger than Pandas can scale).

Q5: Are there any notes for "moving from Pandas to Vaex" to help with my orientation?

Q6: Is the notion of having a matrix in RAM, rather than memory mapped, less of a focus for Vaex? Maybe I'm trying to solve a problem that Vaex (in this situation) isn't setup to solve well?

Any feedback would be much appreciated! I ask with a view to personal education and my training courses so please forgive and point me in the right direction if I'm missing some background material I should be reading.

Cheers, Ian.

**Comment by ianozsvald** [comment]
For reference I'll link to https://github.com/vaexio/vaex/issues/967 which notes that Object dtypes are slow (as a PyArrow change has to happen on the fly and it'll be fast for strings if that's done by the user) and that roundtripping via HDF5 forces PyArrow which solves this problem. 

I'll also link to https://github.com/vaexio/vaex/issues/946 which notes "The model behind vaex is that the data should live on disk, and it should be immutable" and I think that explains many of my questions above. 

The various articles that float around the internet do seem to say "Pandas too slow? Vaex is great!" without providing clarification for _when_ Vaex makes sense, so maybe some clues could be added to the FAQ to help a user decide when taking on the learning curve for Vaex might result in a strong win?

**Comment by maartenbreddels** [comment]
Hi Ian,

thanks for you questions, and spending time reading the documentation before asking :). As discussed privately with @JovanVeljanoski, I think some of these questions should enter into the FAQ, but lets start answering here.

> Q1: I don't see an equivalent to a Pandas `df.mean(axis=1)` for row-wise operations.

Yes, indeed, I have thought about this, but I haven't found the right way to do this in Vaex. In https://github.com/vaexio/vaex/pull/415 we have explored the idea of supporting nep13/nep18. In this case it would be
```
np.mean(df, axis=X)
```
But since I/we just entered the Python Data API Standards consortium https://data-apis.org/blog/announcing_the_consortium/ I'm putting it on hold a bit. But the idea is to let the dataframe behave very much like a 2d ndarray.



> arr = np.random.random(size=(52, 10_000))
> ...#same code
> dfv = vaex.from_pandas(df) # takes 42 seconds

The latest stable release indeed shows that behaviour, the next release (or if you dare to try the alpha https://pypi.org/project/vaex-core/4.0.0a2/ ) brings that down to 1 second.


> ```
> dfv.mean(list(dfv.columns.keys())) # took too long
> ```

Yes, that also currently very slow, I've reported this in #973 and should be possible to speed up significantly.





> Q2: It looks like building a Vaex DataFrame from Pandas is quick for a few long columns but slow for many short columns - is Vaex setup to work on fewer longer columns?

We focus on tall skinny dataframes, but I have to say that we should be able to go wider, 1000 columns should not lead to performance issues, 10_000 should be possible, but not tested much, but I would say 100_000 columns is out of scope for now.




> Q3: Calculating the column-wise mean on a 10_000 x 52 matrix is fast but doing the same on a 52 x 10_000 matrix is slow - what's going on with the architecture (or my mangling of things?) to make the speed difference so big?

Vaex is column-oriented, it does not keep a contiguous matrix into memory. Which means in the first case, it hold 52 arrays, and will do 52 calculations on them, and all the bookkeeping in setting up the calculations will have to work with only 52 columns. However, the transpose of that, means it has to work with 10_000 columns, and all the bookingkeeping has to setup work for those 10_000 calculations, which gives some overhead. Because this use case is not tested a lot, the overhead it currently too large, and we can absolutely improve on it. Nonetheless, I think the second case will always be slower (but we can make it much faster!).


> Q4: I don't see a Transpose (Pandas `.T`) operation, I'm guessing we're not expected to want to turn our matrix around? I appreciate that this might be a "Pandas centric" question (in part I ask because I know that Modin makes a point of how it _can_ scale a transpose to be far larger than Pandas can scale).

Yes, in my mind, it does not make sense to transpose tall dataframes with non-homogeneous datatypes. I think it's great that Pandas can do that, and if cleaning up data requires this, I think this task should be offloaded to Pandas. Tools that focus on efficiency should not try to go there I think. So I see Pandas staying around for a long time to support these 'dirty data' operations, and a pre-pre-processing step, before continuing on a more tidy dataframe with Vaex.




> Q5: Are there any notes for "moving from Pandas to Vaex" to help with my orientation?

They are scattered around, and maybe it makes sense to have this written down, possibly in the FAQ (@JovanVeljanoski ?).


> Q6: Is the notion of having a matrix in RAM, rather than memory mapped, less of a focus for Vaex? Maybe I'm trying to solve a problem that Vaex (in this situation) isn't setup to solve well?

In-memory is fine, as far as Vaex is concerned, only when the size of the dataframe becomes too large to fit into memory, it would need to live on disk.

I think the sweet spot for vaex is tall dataframes, 10m-1billion rows, 1-100 columns. I think we should expand the number of columns a bit more, and moving that up to 1000 should be fast, and up to 10_000 workable. Anything highly dirty, e.g. very non-tabular, nested json etc, something that needs transposing, would need to be preprocessed with Pandas.

For smaller datasets, the only Vaex advantage you would currently is the automatic ml-pipelines. We are thinking about data lineage as well.

I hope I answered all your questions!



@JovanVeljanoski let me know if I missed anything

**Comment by ianozsvald** [comment]
Many thanks for the notes, they're very useful. I'm giving a talk at ODSC on "Sprinting Pandas" this weekend and I have a slide on "When you might want to Vaex", so I'll include some of your notes (I have the same for Modin & Dask) and I've linked back to this thread already so other folk can peruse and consider your points - cheers!
